### ISSUE TITLE
♻ refactor(bal-nav): Navigation Refactoring Issues

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#1002]
### Found Issues

- [x] **Popup indicator is not positioned correctly**

_Desktop:_   
<img width="366" alt="Bildschirmfoto 2023-07-19 um 12 00 29" src="https://github.com/baloise/design-system/assets/72393447/c3d5b456-625b-469f-a99b-2653b6942d79">

<img width="477" alt="Bildschirmfoto 2023-07-19 um 12 01 00" src="https://github.com/baloise/design-system/assets/72393447/b6a91f0b-1b96-4b37-a20e-b0f86fb86324">

_Mobile:_
<img width="378" alt="Bildschirmfoto 2023-07-19 um 12 01 25" src="https://github.com/baloise/design-system/assets/72393447/4b34253b-f4cb-4615-a196-06d8bd9ca46a">

(The "container" class overwrites the "bal-popup__container" class -> position fixed is overwritten)

- [x] **Links for Meta Buttons without Popup (location) are not working**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
done with #911

**Comment by GinaBiondo** [comment]
Issues still remain with version 14.0.1
