### ISSUE TITLE
🔧 chore(documentation): add setup instructions for angular standalone project

### ISSUE THREAD

**Issue by svene** [baloise/design-system#1003]
### Summary

Currently the getting-started docs describle how to setup the design system for an angular project.
It is still based on angular modules.

I think an additional setup variant should be added which describes how to set it up for an angular project which does not use angular modules anymore but standalone components.

This would be very helpful for people setting up a new, modern angular project who want to use the design system.

### Use Case

getting started with DS

### Preferred Solution

Two setup documentations (not mixed): One for angular modules, a second one for the standalone approach.

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @svene , yes we will do that. Thanks for reporting.

To get it running just import BaloiseDesignSystemModule in the `app.config.ts` file.

```typescript
import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { BaloiseDesignSystemModule } from '@baloise/design-system-components-angular';

export const appConfig: ApplicationConfig = {
  providers: [importProvidersFrom(BaloiseDesignSystemModule.forRoot())],
};

```

**Comment by hirsch88** [comment]
added to the new docs
