### ISSUE TITLE
🐛 fix(bal-navigation-popover): Arrow property not working

### ISSUE THREAD

**Issue by 1lander** [baloise/design-system#1011]
### Current Behavior

When the arrow property is added to the bal-navigation-popover no arrow is displayed. 

### Expected Behavior

I expect an arrow to be displayed next to the label. It also does not seem to work in the documentation example https://design.baloise.dev/?path=/docs/components-popover--arrow

### Steps to Reproduce

1. add arrow property to a bal-navigation-popover

### Version

13.4.3

### Browsers

Chrome

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @1lander 

Currently we are refactoring the navigation component. Will be non-blocking, however please wait until we have this done.

Thanks

**Comment by hirsch88** [comment]
Hi @1lander, version 14.0.1 is released with the new bar-nav component. hope that fixes your issue.
