### ISSUE TITLE
🎨  chore(tracking): options for components to understand user-behaviour

### ISSUE THREAD

**Issue by clastzoo** [baloise/design-system#1029]
### Summary

Our design-system components are used in several projects. To better understand the user-behaviour while interacting with components we asked use the following questions.

- Can we track the usage of a component within a project where a ?
- Is there a way to create statistics/analytics to understand which elements are used the most?
- How can we achieve to understand where we can have a direct impact by improving components?
- - Or is it only possible by guiding the project teams who are using the system, to enable them easily to implements tracking/.monitoring?

### Use Case

As a design system owner i want to understand where we can improve the impact our design system is creating.

### Additional Information

**General**
https://zeroheight.com/blog/how-to-measure-your-design-system/ 
https://uxdesign.cc/stop-building-design-systems-without-a-tracker-2568f102362d

**Technical**
https://engineering.brevo.com/how-to-track-design-system-adoption/
https://engineering.talkdesk.com/metrics-that-matter-measuring-the-impact-of-the-cobalt-design-system-part-ii-20ea2c131be1
https://www.productboard.com/blog/how-we-measure-adoption-of-a-design-system-at-productboard/

https://github.com/rangle/radius-tracker @hirsch88 

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
We close this issue due to inactivity
