### ISSUE TITLE
🎨 chore: align naming of figma and storybook components

### ISSUE THREAD

**Issue by samira-liebendoerfer** [baloise/design-system#1031]
### Summary

**Problem:** 
some components are named differently in the [DS Storybook](https://design.baloise.dev/?path=/docs/welcome--page) than the ones in the [DS Figma](https://www.figma.com/file/lgDn2QZqoJJlYzGTe6cOmr/%F0%9F%A7%A9-Components?type=design&mode=design&t=ng00U4Uw9cSj4Dnp-1). This has caused some confusion when talking about the components. 

**Solution:** 
- Adjust component names to the one in Storybook
- Adjust component props to the one in Storybook
- Check if all the variants are in Figma

Source of truth for the names of the components = Storybook

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
We close this issue due to inactivity

**Comment by hirsch88** [comment]
We close this issue due to inactivity

**Comment by hirsch88** [comment]
We close this issue due to inactivity
