### ISSUE TITLE
:bug: fix(bal-select): Is required validation should appear later

### ISSUE THREAD

**Issue by NoraKurzbein** [baloise/design-system#1032]
### Current Behavior

If you have a select with a isRequired validator and you choose the very first value, select flickers shortly red. If you kepp the mouse down during the very first click you can see that it's red then and is-invalid classes are added. If you release the mouse select is valid.

### Expected Behavior

If I choose a valid value in a bal-select it should not appear read at any time. 

### Steps to Reproduce

1. Add a bal-select to your application 
2. Configure isRequired validator 
3. choose very first value (keep the mouse pressed to see it for a longer time)

### Version

13.6.1

### Browsers

Chrome

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Done with version [13.7.1](https://github.com/orgs/baloise/projects/5/views/1?pane=issue&itemId=36976035#1371)
