### ISSUE TITLE
🔧 chore: refine form validation

### ISSUE THREAD

**Issue by samira-liebendoerfer** [baloise/design-system#1034]
### Summary

The objective of this task is to establish the criteria for determining when a form input should be flagged as invalid (indicated by a red highlight) for the user.

### Problem
- a consistent handling of form validation is missing 
- concerns all the form components

### Next steps
- [ ] Gather Use Cases (Portal, Calculators, Website...)
- [ ] Develop a solution with best UX practices
- [ ] Consider accessibility standards (AA) 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
We close this issue due to inactivity
