### ISSUE TITLE
✨ feat(pagination): add items per page and show current visible items 1 - 10

### ISSUE THREAD

**Issue by SandraVucko** [baloise/design-system#1045]
### Summary

Lists have pagination currently an max items per pages are set per default. 
Change Request: 
1. To have an selection field to define number of items per page. 
2. Display the current shown item numbers for instance: 1 - 10 fromm 99

### Use Case

List with employees is displayed -> default number of items per page = 10, the fisrt 10 employees are displayed, the indication shows 1- 10 from 89.
User selects items per page = 50, the employee list shows 50 employees and the indication 1 - 50 from 89.
User goes to second page, indication is 51 - 89 from 89.
User enters a filter and the indication refreshes accordingly, example 1 - 15 from 15 (we still have 50 items per page)

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SandraVucko** [comment]
![EmployeeList](https://github.com/baloise/design-system/assets/145654403/240fe2a2-b5fb-4be1-845b-f93f527d017e)

**Comment by hirsch88** [comment]
Hi @SandraVucko 

If you are using the [AG-Grid](https://www.ag-grid.com) library, please utilise their pagination option (link provided below).
https://www.ag-grid.com/javascript-data-grid/row-pagination/

If you are utilising a basic HTML table, you have the option to stack the elements into a single row, as shown in the example below.

```html
<bal-stack space="auto">
  <bal-text bold style="width: 8rem;">1-10 von 92</bal-text>
  <bal-pagination page-range="3" total-pages="20" value="2"></bal-pagination>
  <bal-field style="width: 8rem;">
    <bal-field-label>Pro Seite</bal-field-label>
    <bal-field-control>
      <bal-select value="10">
        <bal-select-option value="10" label="10">10</bal-select-option>
        <bal-select-option value="20" label="20">20</bal-select-option>
        <bal-select-option value="30" label="30">30</bal-select-option>
      </bal-select>
    </bal-field-control>
  </bal-field>
</bal-stack>
```

https://codesandbox.io/s/angular-forked-zs3zls?file=/src/app/example.component.html
