### ISSUE TITLE
:bug: fix(component): open modal in bal-data-value

### ISSUE THREAD

**Issue by baengel** [baloise/design-system#1076]
### Current Behavior

If I click on the pen-button, it triggers the event twice, see here the example:
codesandbox.io/s/angular-forked-98tdjn?file=/src/app/example.component.html:132-146

### Expected Behavior

the event will be triggered only once

### Steps to Reproduce

1. create a ui in angular like:
 <bal-data-value (balClick)="gugus();" [editable]="true">Value</bal-data-value>
2. execute 
3. click on button
4. gugus will be triggered twice.

### Version

14.0.2

### Browsers

Chrome

### Code Reproduction URL

https://codesandbox.io/s/angular-forked-98tdjn?file=/src/app/example.component.html:131-229

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
done with release 14.0.3
