### ISSUE TITLE
:speech_balloon: question(date picker): eager loading

### ISSUE THREAD

**Issue by glennverschooren** [baloise/design-system#1087]
### Question

Hi,

Is it possible to preload a react component instead of lazy loading the component?
Our baloise datepickers are performing bad on first load when using low/mid end mobile devices.

Best regards

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @glennverschooren this is the default behaviour of Stencil components architecture.
