### ISSUE TITLE
:bug: fix(bal-input): Fix setFocus on overlay

### ISSUE THREAD

**Issue by NoraKurzbein** [baloise/design-system#1165]
### Current Behavior

I try to set the focus on the first bal-input after open a overlay. 
Code in HTML: 
<bal-input [placeholder]="'labels.garageSelection.searchInput.placeholder' | translate"
                 [formControl]="searchControl"
                 #searchControlInput></bal-input>

Code in Typescript: 
@ViewChild('searchControlInput') searchControlInput: ProxyComponent<Components.BalInput>;
 ngAfterViewInit(){
    this.searchControlInput.el.setFocus();
  }

But the bal-input has no focus after overlay is loaded. 
HINT: If I try exact the same code on a page it works fine. 

### Expected Behavior

After the overlay is loaded the bal-input should have the focus. 

### Steps to Reproduce

Take my code from description in current behavior. 
bal-input is within a bal-input-group, the whole component is in a bal-modal

### Version

14.3.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @NoraKurzbein 

For now try this in the modal component. With `waitAfterIdleCallback` we wait until the browser has finished working and goes into idle.

```ts
  async ngAfterViewInit() {
    await waitAfterIdleCallback()
    this.myInput.el.setFocus()
  }
```

**Comment by NoraKurzbein** [comment]
Hi @hirsch88  

Thank's for the proposal unfortunately the bal-input still has no focus...

**Comment by mladenplaninicic** [comment]
Hi @NoraKurzbein, here is the solution: 

```js
  @ViewChild('myInput')
  myInput!: ProxyComponent<Components.BalInput>

  @Input() modalDidPresent!: Promise<void>

  async ngAfterViewInit() {
    await this.modalDidPresent
    this.myInput.el.setFocus()
  }
```
In the modal component, an @Input() property named modalDidPresent is defined, which is a Promise<void>.

In the ngAfterViewInit lifecycle hook, we are awaiting the resolution of the modalDidPresent promise and then calling the setFocus method on the input field.

```js
  modal!: HTMLBalModalElement

  constructor(private modalService: BalModalService) {}

  async open() {
    let modalDidPresent = () => void 0
    this.modal = await this.modalService.create({
      component: ModalComponent,
      componentProps: {
        firstName: 'Peter',
        lastName: 'Parker',
        modalDidPresent: new Promise(resolve => (modalDidPresent = resolve as any)),
      },
    })
    await this.modal.present()
    modalDidPresent()
  }
```

In the open method, we initialize modalDidPresent, and then we pass a new Promise to the ModalComponent's modalDidPresent input. The resolve function of this promise is assigned to modalDidPresent.

After the modal is presented, we call modalDidPresent() to resolve the promise. This triggers the execution of the code inside the ngAfterViewInit hook in the modal component, setting the focus on the input field.

Please let us know if this solution works for you.
