### ISSUE TITLE
🐛  fix(bal-navigation): Active State remains for closed first level navigation

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#1244]
### Current Behavior

The active state for closed menu items in the first level main navigation remains even if the menu is closed

### Expected Behavior

When the menu is closed, no item should be marked as active

### Steps to Reproduce

regular usage

### Version

15.0.2

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Device

Desktop

### Additional Information

On page load:
<img width="1601" alt="Bildschirmfoto 2023-12-20 um 14 21 15" src="https://github.com/baloise/design-system/assets/72393447/2cbeb2f7-7dc4-4b6a-b974-606000b4fe4f">

Opened and closed:
<img width="1634" alt="Bildschirmfoto 2023-12-20 um 14 21 44" src="https://github.com/baloise/design-system/assets/72393447/8b833a80-9598-4a9e-83cb-e702046452fa">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
@clastzoo is the behaviour correct like that

**Comment by hirsch88** [comment]
close due to inactivity
