### ISSUE TITLE
:sparkles: feat(component): improve select buttons

### ISSUE THREAD

**Issue by lrommerskirchen** [baloise/design-system#1272]
### Summary

remove background colour of selected-state and only fill radio

### Use Case

if "select buttons" are already pre-selected as default (e.g. claim-u), then the background colour brings too much focus in compared to the content. 
![image](https://github.com/baloise/design-system/assets/132366430/26eda119-06ca-49ff-ac10-73848aa26daa)

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
We close this issue due to inactivity
