### ISSUE TITLE
fix(bal-field-label): Field hint does not get displayed behind the field label when the label text is wrapping to multiple lines

### ISSUE THREAD

**Issue by 1lander** [baloise/design-system#1285]
### Current Behavior

![Screenshot 2024-01-18 at 11 23 59](https://github.com/baloise/design-system/assets/34511413/d448d8ec-8bf5-430d-a7bf-52f700ffaf28)

When the label is long and wraps the text the Field hint does not get displayed behind the last word of the text

### Expected Behavior

The Hint should appear at the end of the text like when it's not wrapped

### Steps to Reproduce

1. Add a label with a long text that wraps with a hint at the end

### Version

15.2.0

### Browsers

Chrome

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mladenplaninicic** [comment]
this issue is fixed, it will come with the next release.
