### ISSUE TITLE
:bug: fix(component): Modal is not present

### ISSUE THREAD

**Issue by lazaki** [baloise/design-system#1319]
### Current Behavior

When we used BalModalService -> create method modal is not present after update to Angular version to 17.1.1 and design system to 15.2.2., I saw on other project two workarounds, one is to configure angular optimisation for scripts to false, which has as side effect that main.js is not minified and uglified and the second one is to import legacy DS.

### Expected Behavior

When call BalModalService create the modal is shown.

### Steps to Reproduce

1. Use Design system version 15.2.2
2. Use Angular version 17.1.1
3. Start application
4. Try to open modal

### Version

15.2.2

### Browsers

Chrome

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
@lazaki you need to use the legacy package since your project is still working with the webpack builder

**Comment by hirsch88** [comment]
linked to https://github.com/ionic-team/ionic-framework/issues/28385
