### ISSUE TITLE
🔧 chore(documentation): Fix link toward ui icons

### ISSUE THREAD

**Issue by nobilo** [baloise/design-system#1338]
### Current Behavior

https://design.baloise.dev/?path=/docs/foundation-icons--documentation#overview
clicking on marked ui-icons is not working:
![image](https://github.com/baloise/design-system/assets/11984467/1bd49b73-cde8-4017-b94f-8ce52a85442a)

### Expected Behavior

should link toward all icons, i guess this page;
https://design.baloise.dev/?path=/docs/foundation-iconography--documentation

### Steps to Reproduce

go to page and click

### Version

15.2.4

### Browsers

Chrome

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yannickholzenkamp** [comment]
Hi @nobilo 
I just checked the issue and the documentation of the iconography page changed and the reported link is not on the page anymore. Will close the issue. Please reopen, in case it's still not working.
