### ISSUE TITLE
:bug: fix(bal-select): please confirm the current behaviour is correct

### ISSUE THREAD

**Issue by yannickholzenkamp** [baloise/design-system#1339]
### Current Behavior

Scenario:

- I have a bal-select with the options "1994" and "1995"
- I choose an element from the list e.g. "1994"
- Afterwards I alter the set of options, let's say "red" and "green"
- The current value of the bal-select will stay as"1994"
- Afterwards I set the value to undefined, null or ""
- The current value of the bal-select will stay as "1994"
- Afterwards I set the value to "red"
- The current value of the bal-select will change to "red"

Please confirm altering the options should *not* reset the display of the current value.
Please confirm setting the value to undefined should *not* reset the display of the current value.

See codesandbox below.

### Expected Behavior

I would have expected the displayed value to be resetted after the options were changed, or at least after the value is set to "undefined".

### Steps to Reproduce

see above

### Version

15.2.1

### Code Reproduction URL

https://codesandbox.io/p/sandbox/angular-forked-pp8j22?file=%2Fsrc%2Fapp%2Fexample.component.ts%3A24%2C48&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt4kla7o0006356hubb1f5e1%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt4kla7o0002356hun1fyql3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt4kla7o0003356h5av2ur1d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt4kla7o0005356h62m2o1hd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt4kla7o0002356hun1fyql3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt4kla7o0001356hzhhwlflv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clt4kmodd004u356h847frmr5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A24%252C%2522startColumn%2522%253A48%252C%2522endLineNumber%2522%253A24%252C%2522endColumn%2522%253A48%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp%252Fexample.component.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clt4kla7o0002356hun1fyql3%2522%252C%2522activeTabId%2522%253A%2522clt4kmodd004u356h847frmr5%2522%257D%252C%2522clt4kla7o0005356h62m2o1hd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt4kla7o0004356h5ei4494t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clt4kla7o0005356h62m2o1hd%2522%252C%2522activeTabId%2522%253A%2522clt4kla7o0004356h5ei4494t%2522%257D%252C%2522clt4kla7o0003356h5av2ur1d%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clt4kla7o0003356h5av2ur1d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Please use the new bal-dropdown
