### ISSUE TITLE
:bug: fix(Date): update date range / break of year

### ISSUE THREAD

**Issue by Feamusbal** [baloise/design-system#1358]
### Current Behavior

If only entering two digits for the year (e.g., 12.12.60) the Date component auto completes the first two digits for the year. The break of year changes to 20XX until the 60s (e.g. 12.12.60 becomes-> 12.12.2060). This does not match the users expected mental model as they are more likely to enter  1960 than 2060) 

### Expected Behavior

For numbers between 35->99 we should use 19XX format. The lower number should update every year (next year 36-99). 
For numbers between 00->34 we should use 20XX format. The high number should update every year (next year 00-35).

Break of Year should be added as a properity to the component. 

### Steps to Reproduce

see above

### Version

v15

### Additional Information

I entered it as a bug as it isn't a feature

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
@Feamusbal this change can only be done globally and not per use case

**Comment by hirsch88** [comment]
```ts
  public static setTwoDigitCutoffYear(cutoff = 10) {
    Settings.twoDigitCutoffYear = ((new Date()).getFullYear() % 100) + cutoff
  }
```

I can do this so today plus 10 years in the future is possible for 2000 rest will be 1900. So the cutoff year will be now 2034 and 35 will be 1935.

**Comment by Feamusbal** [comment]
@hirsch88 will it be easy to update it over time? So that next year (2025)  it will be 35->2035 and 36-> 1936?
