### ISSUE TITLE
✨  feat(date): Possibility to return invalid date

### ISSUE THREAD

**Issue by SandraVucko** [baloise/design-system#1370]
### Question

How can we distinguish in the date picker whether an incorrect date (e.g. 38.15.2024) has been entered or whether no date has been entered? We would like to throw a specific error message in the first case.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mmarinkov** [comment]
- [ ] add new prop to enable component to send invalid dates back
- [ ] add warning hints if invalid date -> check with UX
