### ISSUE TITLE
✨ feat(icons): Add a fourth RTE list icon

### ISSUE THREAD

**Issue by fabio-tedesco** [baloise/design-system#1372]
### Summary

As requested on ticket BARE-2005 a fourth icon for the list in rte is needed like in the attached picture. 
![image-2024-03-26-12-29-29-325](https://github.com/baloise/design-system/assets/94684353/a10bad13-9881-41ce-9b08-6e0c714e7b3f)

### Use Case

Another icon can be chosen for the list in rte.

### Preferred Solution

Here https://github.com/baloise/design-system/blob/main/packages/css/src/core/list.sass the css can be added about

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
@clastzoo Can you provide us the icon
