### ISSUE TITLE
:speech_balloon: question(component): SSR and SSG

### ISSUE THREAD

**Issue by glennverschooren** [baloise/design-system#1387]
### Question

Is it possible to hydrate HTML from a Node server using SSR or SSG?

https://stenciljs.com/docs/hydrate-app

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by glennverschooren** [comment]
@hirsch88 Any ideas on this? 

We are currently working on a nextjs project and it would be nice if we could server side render the components on initial page load.

**Comment by hirsch88** [comment]
@glennverschooren What is the use case that you use SSR?

The components are not ready for SSR. Would be a great effort and also regarding for testing to keep them working.

**Comment by hirsch88** [comment]
We will add more documentation to contribute to the DS to enable SSR.

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/pull/1410
