### ISSUE TITLE
:bug: New module ds-icons can not be used with typescript 

### ISSUE THREAD

**Issue by glennverschooren** [baloise/design-system#1394]
### Current Behavior

```
import React from 'react'

import { useBaloiseDesignSystem, BalApp } from '@baloise/ds-react'
import { balIconStarFull } from '@baloise/ds-icons' => Module '"@baloise/ds-icons"' has no exported member 'balIconStarFull'.ts(2305)

export default function App() {
  useBaloiseDesignSystem({
    defaults: {
      icons: { balIconStarFull },
    },
  })

  return <BalApp>...</BalApp>
}
```

### Expected Behavior

ballconStartFull is known as an exported member by Typescript.

### Steps to Reproduce

1.  Import baloise icon

### Version

16.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @glennverschooren , just created a new react app with create-react-app with typescript and it worked.
could clear your rpm cache or remove the node_modules folder
