### ISSUE TITLE
:sparkles: feat(header): add component for header

### ISSUE THREAD

**Issue by lrommerskirchen** [baloise/design-system#1395]
### Summary

Header component created with the tab components. So, we have a component all portals can use and have the same pattern across portal applications.
![image](https://github.com/baloise/design-system/assets/132366430/9dbfd3ab-f078-4b48-b634-e9020153def5)

### Use Case

Needed for any application that provides a portal with different pages and functions for users to interact with.

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
This can be done with a bat-stack component and shared between the portals.
