### ISSUE TITLE
:bug: fix(bal-modal): opening bal-modal leads to page scroll to top

### ISSUE THREAD

**Issue by tri-vo-mesoneer** [baloise/design-system#1396]
### Current Behavior

bal-modal does not restore the scroll position.
If the page is long, then opening the modal which is in the bottom of the page, leads to the page will be scrolled to top when bal-modal is opened.

### Expected Behavior

I expect that the page will keep the scroll postion when bal-modal is opened or closed.

### Steps to Reproduce

1. You can open `Code Sandbox` in the Baloise document [link](https://design.baloise.dev/?path=/docs/components-feedback-modal--documentation).
2. Just simply add some element above bal-modal in order to make the page longer.
3. Click on button to open modal and you will see the page is scrolled to top.
![BDS_modal](https://github.com/baloise/design-system/assets/106668384/d6fe63f1-bf95-4387-9810-e8dfec773f84)

### Version

latest

### Browsers

Chrome, Microsoft Edge

### Device

Desktop

### Code Reproduction URL

https://codesandbox.io/p/sandbox/angular-forked-p65s8z?file=%2Fsrc%2Fapp%2Fexample.component.html%3A5%2C1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
A builded angular app still does scroll to the top

**Comment by hirsch88** [comment]
Could not reproduce the issue
@FilipMarkovski please try to update the Design System and clear the cache.

**Comment by hirsch88** [comment]
created a version with logs to investigate the angular issue
16.2.0-snapshot.1402-c52849609

**Comment by hirsch88** [comment]
@FilipMarkovski 16.2.0-snapshot.1402-8b748b200

**Comment by FilipMarkovski** [comment]
@hirsch88 If you can, keep this issue open until the required libraries are updated to the latest version of Design System, because that change will come in some of the future sprints.

**Comment by FilipMarkovski** [comment]
The problem is definitely within the two internal libraries that are indirectly fetching the legacy @baloise/design-system-components. We just saw the results after we got rid of both of them.

If you want, you can close this ticket as "resolved". For anybody else reading this issue, run "npm ls @baloise/design-system-components". If one of the dependencies are still fetching design system < v16, you should upgrade them.
