### ISSUE TITLE
🔧  chore(docs): Checkbox Storybook Page is broken

### ISSUE THREAD

**Issue by clastzoo** [baloise/design-system#1399]
### Current Behavior

https://design.baloise.dev/?path=/docs/components-form-checkbox--documentation

### Expected Behavior

Failed to fetch dynamically imported module: https://design.baloise.dev/assets/bal-checkbox-ByyA2JXN.js
TypeError: Failed to fetch dynamically imported module: https://design.baloise.dev/assets/bal-checkbox-ByyA2JXN.js

### Steps to Reproduce

1. Go to https://design.baloise.dev/?path=/docs/components-form-checkbox--documentation

### Version

16.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
This looks like a storybook issue. Component seems to work fine therefore I close this issue
