### ISSUE TITLE
:bug: fix(bal-file-upload): Unable to upload .docx files.

### ISSUE THREAD

**Issue by 1lander** [baloise/design-system#1411]
### Current Behavior

When adding .docx files to the accept property I'm able to select docx files but when I click to upload an error(file_name.docx => BAD_EXTENSION) gets thrown

### Expected Behavior

For the document to be uploaded and appear in the file list.

### Steps to Reproduce

1. add docx file type to the accept property
2. upload docx file
3. see error

### Version

16.1.0

### Browsers

Chrome

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/blob/main/packages/core/src/components/bal-file-upload/utils/file-validation.util.ts#L25

**Comment by mmarinkov** [comment]
Hi @1lander,
I assume the chosen mime type is not correct. Adding "application/vnd.openxmlformats-officedocument.wordprocessingml.document" to the accept property should solve the issue. Can you please test this change?

**Comment by 1lander** [comment]
> Hi @1lander, I assume the chosen mime type is not correct. Adding "application/vnd.openxmlformats-officedocument.wordprocessingml.document" to the accept property should solve the issue. Can you please test this change?

Yes, adding this to my accept property works. Thanks!
