### ISSUE TITLE
✨ feat: Scope Baloise Web Components into a custom web component

### ISSUE THREAD

**Issue by glennverschooren** [baloise/design-system#1412]
### Question

I'm working on a web component for Baloise that needs to replace an iframe. There are three key components involved:

1. The Baloise.be website where I need to load the component (CMS Magnolia).
2. The Baloise web components  aka Baloise design system (an open-source GitHub project).
3. The custom web component (created with stencil) that I need to create, which internally also uses the Baloise web components.

The Baloise.be website loads a version of the Baloise web components since these are also used on the website. The custom web component also relies on these components. Currently, the custom web component uses the Baloise web components loaded by the Baloise.be website.

However, this can cause problems if the version of the Baloise web components is updated on the Baloise.be website without the custom web component being adjusted accordingly.

Does anyone know if there is a way to namespace these web components so that the custom web component can run its own version of the Baloise web components?

For additional context:

- This is not using any framework, just plain JavaScript.
- The Baloise components are loaded into the Baloise website via a script tag.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
@glennverschooren as far as I know that is not possible. We have special templates on magnolia for that case or use a standalone approach to not integrate the app into a cms.
