### ISSUE TITLE
:wheelchair: a11y(productslider): Link List

### ISSUE THREAD

**Issue by carolabes** [baloise/design-system#1417]
### Description of this issue

* screenreader does not recognize how many items the list contains

<img width="1504" alt="productslider-linklist" src="https://github.com/baloise/design-system/assets/172396366/2f406afd-f151-40da-aa08-8b012948f722">

### How to fix it

* implement as linklist

### Additional Information

Level A
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
ready to be released with the next version after 16.3.0
