### ISSUE TITLE
:bug: fix(bal-form | submit): Submit only triggered after second click for mobile viewports

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#1424]
### Current Behavior

Currently the submit button in forms needs to be pressed twice on mobile viewports to trigger a submit. This seems to be connected to the focus somehow not being handled correctly.

### Expected Behavior

The submit or other actions should be triggered immediately on first click

### Steps to Reproduce

open form on mobile device and trigger submit

### Version

16.2.1

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Device

Mobile, Tablet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @GinaBiondo-aperto could you please provide us a link so we can reproduce that

**Comment by GinaBiondo** [comment]
Hey @hirsch88 :) Found this form as an example:
https://www.baloise.lu/de/privatekunden/mein-geld-und-meine-zukunft/baloise-life-plan.html

**Comment by hirsch88** [comment]
@GinaBiondo-aperto I am not able to reproduce it

**Comment by GinaBiondo** [comment]
Hey @hirsch88 , sorry. for the wrong link. Apparently the behavior only occurs for submit buttons in overlays. An example could be found here in the overlay that presents itself after the form is filled in and the user is asked to enter their email address: https://www.baloise.ch/de/unternehmenskunden/versichern/kmu-versicherungs-check-ihr-ergebnis.html
<img width="369" alt="Bildschirmfoto 2024-09-06 um 09 42 58" src="https://github.com/user-attachments/assets/f3a0c918-bdca-4883-9fc7-68f0e5e11eac">
<img width="372" alt="Bildschirmfoto 2024-09-06 um 09 43 30" src="https://github.com/user-attachments/assets/e360158d-7aa4-479a-ab03-dd1d02422ecd">
