### ISSUE TITLE
:bug: fix(bal-nav): popup arrow visible on mobile

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#1426]
### Current Behavior

When adding a popup (search, login etc) to the navigation, the popup indicator is shown on mobile in the upper left corner.
![BARE-2141_white_square](https://github.com/baloise/design-system/assets/72393447/61e55f62-f8df-4750-8fdb-389b53ca2719)

### Expected Behavior

The indicator should only be visible for desktop

### Steps to Reproduce

add navigation with popup

### Version

16.2.1

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Device

Mobile, Tablet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/blob/main/packages/core/src/components/bal-popup/variants/fullscreen-variant.renderer.ts#L18C12-L18C28

hideArrowElement instead of showing it

**Comment by GinaBiondo** [comment]
@m4rc0z seems as if the arrow prop from the bal-popup is causing the issue. We are currently using it on the popups for the navigation. In the storybook example however it seems to be omitted. Let me know if this is helpful for you :)
