### ISSUE TITLE
:bug: fix(bal-file-upload): File Chooser not triggered correctly

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#1442]
### Current Behavior

The file chooser is not triggered correctly on click. There is no consistent behavior to describe this bug. It happens mostly in FireFox but also in Chrome sometimes. Safari seems fine (sus!). The file upload still works when dragging files inside.

It is very possible that this is somehow caused by our form but we were not able to finde the issue so far. An example where we've noticed this issue is this one: https://www.baloise.de/de/kontakt-service/schaden-melden/hausrat.html

### Expected Behavior

The file chooser should open on every click.

### Steps to Reproduce

Use fiel upload

### Version

16.2.1

### Browsers

Firefox, Chrome, Microsoft Edge

### Device

Mobile, Tablet, Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by m4rc0z** [comment]
Debugged within Edge and found out that there is somewhere a blockClickEvent function which checks the target type. This is undefined ins some cases. The function looks like this:

`blockClickEvent(i) {
        "file" === i.target.type && this.limitReached && i.preventDefault()
    }`

Since this is not on our Code Base @GinaBiondo-aperto  will have a look at this and inform within this issue what the outcome is.

**Comment by GinaBiondo** [comment]
Hey @m4rc0z unfortunately the behavior is still the same :/

**Comment by m4rc0z** [comment]
Hey @GinaBiondo-aperto we can not reproduce it properly. Also, we can not find the blockClickEvent function within our Code Base. Would it be possible that you provide a CodeSandBox (including Browser Versions where it appears) with the problem that we can isolate it better?

**Comment by m4rc0z** [comment]
Agreed with @GinaBiondo-aperto  to close the issue until it is reproducible in a CodeSandBox to ensure its a Design System issue.
