### ISSUE TITLE
:bug: fix(bal-nav | bal-popup): First Popup is misaligned when opening for the first time

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#1443]
### Current Behavior

https://www.baloise.ch/de/privatkunden.html
When opening the phone popup in the navigation for the first time it is slightly misaligned. Closing and opening it again aligns it perfectly.
This is a minor issue!

### Expected Behavior

All popups should be aligned correctly all the time

### Steps to Reproduce

Use the navigation with meta buttons and popups. See https://www.baloise.ch/de/privatkunden.html

### Version

16.2.1

### Browsers

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
![Image](https://github.com/user-attachments/assets/7276b1d0-afd5-4162-b57d-876379604b75)

**Comment by hirsch88** [comment]
cannot reproduce this issue, therefore we will close it
