### ISSUE TITLE
:speech_balloon: ds output targets

### ISSUE THREAD

**Issue by glennverschooren** [baloise/design-system#1455]
### Question

Hi,

I have been exploring the Baloise Design System and noticed that you have created your own library for generating wrappers for React, Vue, and Angular. I am curious to know why you opted for building a custom solution rather than using the @ionic-team/stencil-ds-output-targets library provided by the Ionic team.

Was there a specific reason or set of requirements that led to this decision? I am particularly interested in understanding the factors that guided your choice and how it benefits the design system.

Thank you for your time and for sharing insights on this matter!

Best regards,
Glenn

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @glennverschooren 

Back in the time when we started there were several bugs in the solution of ionic, therefore we forked it.
In time we event at custom behaviour for angular to handle events a bits simpler.

Do you miss a feature or a bug fix?

**Comment by glennverschooren** [comment]
Hi @hirsch88 

Ok thx for the info!
The ionic team have recently released this SSR feature for nextjs projects and I'm very interested in that.
[SSR](https://github.com/ionic-team/stencil-ds-output-targets/commit/399fe25dc18b21bd2c6b59dc0c8bb65d07b07cb6#diff-0b32dfc2fb3babc581d49702b9cbbbb793f69e5a250a89c79a3fcf3ec919b5bb )

I'm planning to add this feature to the @baloise/ds-react library if possible.
So I'm trying to understand the current setup and what needs to be done to make SSR possible.

grtz

**Comment by hirsch88** [comment]
Hi @glennverschooren 

Looking forward to see a PR from you.
