### ISSUE TITLE
:sparkles: feat(list): Add arrow-down to native css list

### ISSUE THREAD

**Issue by clastzoo** [baloise/design-system#1481]
### Summary

To achive an index list within a blog page we need a new RTE element to avoid creating a new component on Magnolia's side. 
![Bildschirm­foto 2024-10-15 um 13 16 40](https://github.com/user-attachments/assets/96505f6d-6230-4c39-b182-b1938e6ed5a9)

Find the icons here: 
16px ![arrow-down-16](https://github.com/user-attachments/assets/ed97ccc3-4a2d-41bc-94d1-586c1378fcee)
14px ![arrow-down-14](https://github.com/user-attachments/assets/532ef4bd-e33c-4454-b4c2-5743e0d06149)

### Use Case

- RTE List Magnolia

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clastzoo** [comment]
DANKE @hirsch88

**Comment by GinaBiondo** [comment]
To make this work like the other bullet styles for native lists, this icon needs to be available as a css class similar to "has-bullet-circle" and the others.
