### ISSUE TITLE
:bug: fix(bal-time): Component Bug on Edge Browser (Version 130.0.2849.80)

### ISSUE THREAD

**Issue by glennverschooren** [baloise/design-system#1505]
### Current Behavior

The TimeInput component from the Baloise design system is not functioning correctly on the latest version of the Microsoft Edge browser (Version 130.0.2849.80). Users are experiencing issues where the input field gets cleared upon focus and when trying to fill in the time. After multiple attempts, it may eventually accept the input, but this is not consistent or reliable. A video demonstrating the issue is available for reference.

https://github.com/user-attachments/assets/613c6be0-c975-4ad1-86b5-ab8f78238b3b

### Expected Behavior

The TimeInput should work as expected on Microsoft Edge Browsers 

### Steps to Reproduce

1. Fill in a time Value (08:15)
2. unfocus the field

### Version

16.1.0

### Browsers

Microsoft Edge

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by m4rc0z** [comment]
Did a short analysis. Current outcome. Reproducable in Versions 130.* and 131.* with Windows (Tested with LambdaTest).

It seems like in these Versions of Edge the onInput Event of the input is not fired and therefore the change is reverted. Needs to have further investigation.

**Comment by glennverschooren** [comment]
Thx for fixing this issue!
