### ISSUE TITLE
:zap: perf(date): use luxon or date-fns lib

### ISSUE THREAD

**Issue by hirsch88** [baloise/design-system#1508]
### Description of this issue

use only one lib

### Code Reproduction URL

http://localhost:4000/test/seo/01-nav.html

### Performance

92

### Largest Contentful Paint

3.0

### Speed Index

2.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yannickholzenkamp** [comment]
The `luxon` date library is in use in the `BalDate` interface, therefore removing `date-fns` would be preferred, as it will be a non-breaking change.

`date-fns` is used in the `bal-datepicker` and the `date.helper`.
Next steps: Remove deprecated component `bal-datepicker` and remove unused functions in `date.helper`
