### ISSUE TITLE
Support CSP policies for style-src 'self'

### ISSUE THREAD

**Issue by tntho** [baloise/design-system#152]
### Feature Request
We always defines `<meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src *;">` in most of our prod environment, and some components are currently incompatible with a strict Content Security Policy (CSP) of `style-src 'self';`, like `Icon` or `Hints` component, these component generate in-line style tag which violate CSP, they do not work as we expected.

It would be nice if all components are compatible with CSP, just like `Navbar`, `List` or `Data` component which use global css style.

### Question
Is there any trick to pass/avoid CSP without using `unsafe-inline`?

**Comment by hirsch88** [comment]
this is solved with version 3.x.x

- icons are now included svgs
- fonts must be added
