### ISSUE TITLE
:bug: fix(bal-dropdown): multiple input values without chips are not wrapped

### ISSUE THREAD

**Issue by zsofia-oroszi-ibmix** [baloise/design-system#1520]
### Current Behavior

If the chips property is not added, the input field doesn't wrap the values, so it overflows the parent container. 
![Screenshot 2024-11-27 at 12 09 40](https://github.com/user-attachments/assets/5bc63419-36a5-47db-bd62-530a55975af3)

### Expected Behavior

.bal-dropdown__root__content should have text wrap if chips are not applied

### Steps to Reproduce

- create a dropdown with the "multiple" prop (without chips) inside a container with defined width
- select options from dropdown, until the field overflows the container

### Version

16.8.0

### Browsers

Chrome

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @zsofia-oroszi-ibmix,
Could you please provide an URL so we can reproduce this issue.
Thank you

**Comment by hirsch88** [comment]
![Image](https://github.com/user-attachments/assets/7f193312-d194-4480-9fdd-d42e8e47bfd3)

could not reproduce the issue

**Comment by zsofia-oroszi-ibmix** [comment]
Hi @hirsch88, we haven't deployed the bal-dropdown yet, only tested it locally. But I also cannot reproduce the issue anymore, the value is truncated to a single line and the dropdown does not overflow the container.

**Comment by zsofia-oroszi-ibmix** [comment]
Hi @hirsch88, we haven't deployed the bal-dropdown yet, only tested it locally. But I also cannot reproduce the issue anymore, the value is truncated to a single line and the dropdown does not overflow the container.
