### ISSUE TITLE
The font-size and line-height helpers do not match to Soba SOB UI design

### ISSUE THREAD

**Issue by khanpn** [baloise/design-system#158]
Following the design typography of one of Soba projects, the development team has problems with font-size and line-height when using this ui-library.

We could see there were defined classes for title, subtitle and is-size-n (n from 1 to 6). But verifying each size of them the team figured out that the font-size and line-height did not match to the defined typography of Soba (got from design team).

The team cannot create custom stylings to have exactly matched sizes to the defined typography of Soba because doing that we could not control the size of ui-library components. There will be inconsistency between sizes of ui-library components and customized styling of the team.

The team need an unique change to resolve the problem.

And the team is thinking about adjusting sizes on this ui-library.
It would be great of the ui-library can provide classes which matched to the defined typography of Soba. Or the ui-library can provide helpers that can make life of the development be better.

Please have a look at the attached image for better understanding.

You are the best,
Khanh Nguyen

![image](https://user-images.githubusercontent.com/12724432/94770392-ba690580-03de-11eb-817d-9e92ad53463d.png)

**Comment by hirsch88** [comment]
Release changes with
https://github.com/baloise/ui-library/releases/tag/v1.54.0
