### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com until 2020-12-31

### ISSUE THREAD

**Issue by christiansiegel** [baloise/design-system#168]
travis-ci.**org** will be closed down December 31st, 2020

Announcement: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom
Migration guide: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by hirsch88** [comment]
We will move to github actions before that :-)

**Comment by hirsch88** [comment]
Moved to github actions
