### ISSUE TITLE
What is the difference between "@baloise/design-system-components-vue" and "@baloise/ui-library"

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#280]
The doc https://baloise-ui-library.vercel.app/components/essentials/vue.html explain that all components can be acceded from import like

` import { BalCheckbox, BalButton } from '@baloise/design-system-components-vue'`.

But in the starter-kit https://github.com/baloise/vue-starter-kit/blob/vite/src/app/components/HelloWorld.vue#L9 a componant is imported using 

`import { BalButton } from '@baloise/ui-library-vue'`

I don't think the package '@baloise/ui-library-vue' is mentioned in the documentation. Perhaps I mistaking but it doens't seem to be a dependency neither.

The starter kit https://github.com/baloise/vue-starter-kit/blob/master/package.json depend on: 

```
  "dependencies": {
    "@baloise/ui-library": "^4.15.1",
    "@baloise/ui-library-vue": "^4.15.1",
```
Instead of `"@baloise/design-system-components-vue": "^1.3.0",`

Could someone bring some clarification on this? Thanks a lot.

**Comment by hirsch88** [comment]
Hi @gagarine 

The design system was called once ui-library. :-) 
On my todo list is to update the vue starter kit to have the design-system instead of the old name.

So for your app use the @baloise/design-system-components-vue.

Cheers,
Gery

**Comment by gagarine** [comment]
Thanks a lot. Greatly appreciate the quick support.

**Comment by hirsch88** [comment]
Vue Starter Kit is now updated. 🚀 
https://github.com/baloise/vue-starter-kit
