### ISSUE TITLE
bal-radio swap label content that is between tag (first become last)

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#303]
Take a bal-radio with HTML content: 

`<bal-radio name="link-example" value="2">This is a <b>bug?</b></bal-radio>`

Instead of rendering the radio with the label `This is a <b>bug?</b>` the label's elements will be swapped like `<b>bug?</b> This is a`.

I'm using vite, but I don't see how this could be a  problem with the builder.

**Comment by hirsch88** [comment]
Hi @gagarine 

Thats funny bug. For now please use it like this => `<span>This is a <b>bug?</b></span>`.

Cheers,
hirsch

**Comment by hirsch88** [comment]
Hi @gagarine 

This issue will be fixed with this PR => https://github.com/baloise/design-system/pull/310

Cheers,
hirsch
