### ISSUE TITLE
BalSelect fail if data is set to undefined

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#304]
If you have a components such as 
```
<BalSelect expanded id="bal-select" v-model="option">
         <BalSelectOption value="Option1" label="Option1">Option1</BalSelectOption>
         <BalSelectOption value="Option2" label="Option2">Option2</BalSelectOption>
 </BalSelect>
  <BalRadioGroup id="bal-radio" v-model="radio">
            <BalRadio name="radio1" value="radio1">radio1</BalRadio>
            <BalRadio name="radio1" value="prepaid">radio1</BalRadio>
 </BalRadioGroup>
```

Having `option` initial value to `undefined` will generate a `TypeError: this.value.filter is not a function` error and crash vuejs if you change the `BalRadioGroup` before using the `BalSelect`.

**Comment by gagarine** [comment]
A bit related.  Vuejs3 documentation recommend to add an `<option disabled value="">Please select one</option> `https://v3.vuejs.org/guide/forms.html#select to avoid case where iOS user can't select an option if their is no matching value. Is this already managed by BalSelect internally?

**Comment by hirsch88** [comment]
Hi @gagarine 

This issue will be fixed with this PR => https://github.com/baloise/design-system/pull/310

Cheers,
hirsch

**Comment by gagarine** [comment]
**EDIT**: I created a new issue => https://github.com/baloise/design-system/issues/313

Thanks @hirsch88 

I still have an error "TypeError: this.value.filter is not a function" when clicking on the select as my v-model value is undefined at first. I'm doing something wrong?

```
<BalSelect expanded placeholder="Please select one" v-model="myvalue">
              <BalSelectOption v-for="option in options" :key="option" :value="option" :label="option">{{ option }}</BalSelectOption>
</BalSelect>
```
