### ISSUE TITLE
BalDatepicker fail because allowedDates is not a function

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#305]
Using the component like that

`<BalDatepicker name="datepicker" v-model="datepicker" placeholder="TT.MM.JJJJ" trigger-icon />`

will generate an error with  `TypeError: this.allowedDates is not a function` and the component will not be rendered.

**Comment by gagarine** [comment]
Adding `:allowed-dates="() => { return true; }"` is a workaround ...

**Comment by hirsch88** [comment]
Hi @gagarine 

This issue will be fixed with this PR => https://github.com/baloise/design-system/pull/310

Cheers,
hirsch
