### ISSUE TITLE
BalDatepicker prop min do not seem to works

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#306]
It's not 100% clear to me how I should set the default or min date for example.

Apparently BalDatepicker want a string such as `min="2021-07-23"` yet it seems to have no effect.

And why not using a Date object?

**Comment by gagarine** [comment]
v-model is also waiting for a string and not a Date object. Using somethings like `new Date().toISOString().slice(0,10)` works their.

**Comment by hirsch88** [comment]
Hi @gagarine 

This issue will be fixed with this PR => https://github.com/baloise/design-system/pull/310

Cheers,
hirsch
