### ISSUE TITLE
useField return "field is not valid" when the helper validators() is not used

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#309]
It is not possible to use a validator made with  `const isRequired = () => createValidator(BalValidators.isRequired(), 'validator.required')` directly in useField.

```
const {
      errorMessage: firstNameErrorMessage,
      value: firstName,
      name: firstNameName,
    } = useField('firstName', isRequired()))
```

Even when the validator passe it will retourn the error message `firstNameName is not valid.`

Using the helper function validators will works

```
const {
      errorMessage: firstNameErrorMessage,
      value: firstName,
      name: firstNameName,
    } = useField('firstName', validators([ isRequired() ]))
```

As a side note, it would be easier to be able to chain the validator to combine them like with yup : `validators.isRequired().isEmail() `.

**Comment by hirsch88** [comment]
Hi @gagarine 

This issue will be fixed with this PR => https://github.com/baloise/design-system/pull/310

Cheers,
hirsch
