### ISSUE TITLE
Cannot combine validators with vee-validate

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#311]
With vuejs I tried to combine validators using the helper provided like that:

```js
const { errorMessage: phoneNumberErrorMessage, value: phoneNumber } = useField('mobileNumber', validators([isRequired(), isPhone()]));
```

Sadly, it only take the first validator and do not combine them.

I'm using the following validator from BalValidators

```js
import { BalValidators } from '@baloise/design-system-components'
import { useValidator } from '@baloise/design-system-components-vue'
import { i18n } from '../plugins/i18n.plugin'

export { validators } from '@baloise/design-system-components-vue'

const { createValidator } = useValidator(i18n.global.t)

export const isPhone = () =>
  createValidator(BalValidators.isPhone(), 'validator.phone')

export const isRequired = () =>
  createValidator(BalValidators.isRequired(), 'validator.required')
```

**Comment by gagarine** [comment]
Perhaps I miss something their. But all regex validator seem to be invalid if empty. I would do the invert.

Instead of
```js
function validateRegex(regex, value) {
  if (isNil(value)) {
    return false;
  }
  if (typeof value !== 'string') {
    return false;
  }
  return regex.test(value);
}
```

Do this
```js
function validateRegex(regex, value) {
  if (isNil(value)) {
    return true;
  }
  if (typeof value == 'string') {
      return regex.test(value);
  }
}
```

Otherwise how do you validate an email field that is not required?

**Comment by gagarine** [comment]
Looking into it a bit more it seem the validator system is broken. Perhaps it's a small bug somewhere, but at it is it's unusable.

On the following code only `myFirstValidator()` will run and mySecondValidator() will never run even if myFirstValidator() return true.

````js

const myFirstValidator = () => createValidator(function (value) {
    return true
}, 'validator.test1')

const mySecondValidator = () => createValidator(function (value) {
    return false // this never run
}, 'validator.test2')

validators([myFirstValidator(),mySecondValidator()])
````

Is their any test on the validators library? Either I'm stupid and do something 100% wrong.  But otherwise this library need more love in term of quality testing.

From the documentation:
<img width="996" alt="image" src="https://user-images.githubusercontent.com/164074/126872259-a91c2d19-1fc2-4460-ba00-b8a12e0a2ab9.png">

**Comment by gagarine** [comment]
As a side comment, I don't see any benefit of using lodash `isNil(value)` instead of `!value`.

```js
If(`!value`) {
    return true // If value is an empty string, null or undefined return true so other validator can do their job
}
```

Anyway lodash seem strange as you do not support old browsers anyway.

**Comment by hirsch88** [comment]
Hi @gagarine 

I improved the validation part with the PR https://github.com/baloise/design-system/pull/319
Update to version 1.7.0 and test it again.

All validators except `isRequired` do not validate empty values. Thanks for the hint.
For the combination of the validators have a look at our vue example app.

- https://github.com/baloise/design-system/blob/master/examples/vue/src/app/pages/Form.vue
- https://github.com/baloise/design-system/blob/master/examples/vue/src/app/helpers/validators.ts

The first failed validator will return the error message and the following will not be executed. So that we only show one error message to the user.

Hope I could help u
