### ISSUE TITLE
BalInput fire event on every input for change or v-model.lazy

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#322]
Hi,

On an text input element, I want to listen to [onchange](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) but **not** on [input event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event).

I tried both:

`<BalInput  v-model.lazy="value" :name="name"></BalInput>`

`<BalInput  @change="eventHandler" :name="name"></BalInput>`

But the event is fired on every input. For `v-model.lazy` this mean `watchEffect(() => { }` is run on every input.

**My Workaround:**

`<BalInput v-model="value" @balChange="eventHandler" :name="name"></BalInput>`

balChange correctly call the handler during onchange, but this mean I cannot use watchEffect as I intended because `value` is still modified on each input as v-model.lazy does not work.

Their is two issues: 
1) It does not seem possible to use v-model.lazy to avoid listening to input event
2) would be nice to be able to use "normal" @change instead of @balChange for consistency with vuejs documentation. But I guess their is a reasons behind this.

**Comment by hirsch88** [comment]
Hi @gagarine 

Unfortunately, we do not support `.lazy` at this point. Maybe later
The event `input, change ...` are reserved by the native elements so that is why we prefix them.
