### ISSUE TITLE
BalSelect (single) return an array of string

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#323]
BalSelect return an array of string.

If this is a bug or a feature is not clear, but it took me some time to debug as the bug happened inside the template. It woks as intended regarding https://baloise-ui-library.vercel.app/components/components/bal-select.html .

With vuejs returning an array for single select was surprising. Returning directly the string will make it works like vuejs normal select https://v3.vuejs.org/guide/forms.html#select .

Array have limitation, for example using v-model.number will fail with the current implementation.

**Comment by hirsch88** [comment]
Hi @gagarine we added the possibility to the bal select to return single values. :-)
