### ISSUE TITLE
Adding initial files on bal-file-upload

### ISSUE THREAD

**Issue by miguelgmarques** [baloise/design-system#326]
### Summary

Adding an initial files property on the File Upload component

### Justification

While working on the file uploading of an inspection task I came across a problem.
When we refresh the page, the file displayed below the uploading component disappears, since we don't have access to the inner state of the component we have no way to set an initial state for it. 

### Desired UX and success metrics

When the page renders the bal-file-upload will already have uploaded files in it.

### Must-have functionality

Having a initial files property

**Comment by hirsch88** [comment]
This is in work in progress => https://github.com/baloise/design-system/pull/391

Thanks to @sladomic
