### ISSUE TITLE
ag-grid-community seem a require dependency

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#329]
Before I was able to build the DS without the ag-grid-community package (I was not using it). Now it fail apparently because of SASS import.

I didn't dig it and installed the  ag-grid-community package (as I may actually need it). I suspect it may be related to vite update.

I also saw that the new ag-grid-community 22.0.0 use module. It may be simpler to require the dependency and rely on the building system to remove it if not used.

**Comment by hirsch88** [comment]
Hi @gagarine we have no improved that and created a new package for the table.
