### ISSUE TITLE
Support request: How to select a "default" option on BalSelect typeahead?

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#331]
I'm using a BalSelect component with typeahead. The select is an autocomplete with suggestion coming form the server side.

When the user come back to this form, I would like to prefill the input value with the what the user had enter (let's call that uservalue).

I created one BalSelectOption with the uservalue. This part works. I do have a select with one option.

But I want to select this option (or it look empty). I tried multiple things such as `<BalSelect v-model="index"` with index being a `[0]` array. It didn't works.

What is the recommended way to set a default and selected value? Do I need to disable the typehead?

**Comment by lazaki** [comment]
As it is possible to have multiple values selected, I think bal-select accepts array of option values as value.

**Comment by gagarine** [comment]
Yes and I set a reactive value with an array. This array contain just one entry: `[0]`

Somethings like that:
 ` <BalSelect v-model="selectedOption"....
<BalSelectOption value='0' ...`
      </BalSelect>

And in setup:

selectedOption = reactive([0])

It doesn't works to select the default option (the option is not selected when I load the page). But the reactive value is correctly updated if I click on an option.

**Comment by lazaki** [comment]
Maybe it is problem with types (number and string), try to set it to ['0'].

**Comment by gagarine** [comment]
Oh boy. Thanks a lot!
