### ISSUE TITLE
Radio Buttons have inconsistent shade on mobile  

### ISSUE THREAD

**Issue by Gagne87** [baloise/design-system#386]
Testing device: iPhone 12 Mini
Browser: Safari 

Bug description: 
When selected Radio Buttons show an inconsistent shade around the element (compare to screenshot). 

![File](https://user-images.githubusercontent.com/29020214/139028335-b55ca65f-0743-4662-aea3-ca5b58c3433b.jpg)

**Comment by zadewu** [comment]
For this one I override in my scss file. `.bal-radio { outline-style: none; }`

**Comment by hirsch88** [comment]
@zadewu Thanks for the input. I added it in version 9.1.0
