### ISSUE TITLE
[Navbar] Language selection on mobile lacks of functionality

### ISSUE THREAD

**Issue by Gagne87** [baloise/design-system#387]
Bug description: 
On mobile the dropdown does not work anymore. As shown in the screenshot I can click on "Sprache", but nothing will happen. 

Solution needs to be discussed or addressed in the rebranding topic.  

![image](https://user-images.githubusercontent.com/29020214/139028995-acbe8ce4-47d3-442e-aaf6-f201e31025b8.png)

**Comment by hirsch88** [comment]
@Gagne87 We need to create a new design for that and put it maybe into the footer, because this is an action which happens not that often.

**Comment by hirsch88** [comment]
fixed with the new version 10.2.0
https://github.com/baloise/design-system/blob/master/CHANGELOG.md#1020-2022-02-21
