### ISSUE TITLE
balOfferNumber is piping invalid input values

### ISSUE THREAD

**Issue by predrag-arsic** [baloise/design-system#388]
When an invalid string value for offer number, the one that has leading or trailing whitespaces ( " 501234567" or "501234567 " ), is pasted inside the input field which has binded `[value]` property of the `<bal-input>` form still considers this string as invalid, as it should because it's invalid to regex matching, but it is properly piped, giving the user right output in the input field (for mentioned examples it is "50/1.234.567"). This gives the user the wrong sense that the data provided are correct, though they are not.

As I've investigated a bit, the problem comes down to using _parseInt_ inside **balOfferNumber** because this will parse to number regardless of whitespaces. Maybe we should reconsider including the check for the length of the string before doing anything else in this function?

**Comment by hirsch88** [comment]
Hi, @predrag-arsic 

Thanks for creating the issue. 
In the version 2.0.0 the pipes are now in [web-app-utils](https://github.com/baloise/web-app-utils/blob/master/packages/pipes/src/balOfferNumber.ts).

Could you please create there a pr.

1. First add a test with that issue.

Maybe we could use regex like that there.

```javascript
var pipeValue = ' 501234567'
var cleaned = ('' + pipeValue).replace(/\D/g, '').trim();
var match = cleaned.match(/^(\d{2})(\d{1})(\d{3})(\d{3})$/);
if (match) {
    return match[1] + '/' + match[2] + '.' + match[3] + '.' + match[4]
}
return ''
```

Cheers,
Gery

**Comment by predrag-arsic** [comment]
Moved to [web-app-utils](https://github.com/baloise/web-app-utils/issues/19)
