### ISSUE TITLE
 Add closable Toast / Toast with a close button

### ISSUE THREAD

**Issue by RudyBricks** [baloise/design-system#42]
**Issue**
At the moment, one can only open a toast that has no close button by using a Stencil component

Some situations my require to have a toast that stays visible until the user clicks on the close-icon, similar to this one:
[](https://github.com/rfoel/bulma-toast)

**Suggestion**
Add a method like closeOnClick() to balToastController.create(...) chain, so that it generates a permanent toast with an close ("x") button instead of a toast that disappears after a time

**Comment by christiansiegel** [comment]
Do we need a close button? The toasts can already be closed by clicking on them.
PR #49 introduces a duration option. We could define that a negative duration disables automatic closing.

**Comment by RudyBricks** [comment]
Sounds good to me
