### ISSUE TITLE
Datepicker months placeholder is not changing if `max` attribute is defined

### ISSUE THREAD

**Issue by BerSteve** [baloise/design-system#445]
## Detailed description
When `max` attribute is added to component, only current month name is displayed (month placeholder) and month name is always the same when navigating with arrows (calendar changes but not the month placeholder) and only one month option is available. Without `max` attribute everything works as expected.

> What did you expect to happen? What happened instead? What would you like to see changed?
Show all month options and update month placeholder when navigating

> What browser are you working in?
Chrome Version 96.0.4664.110 
## Steps to reproduce the issue
Reproduced by adding `max` attribute. Checked v4 - v8 lib versions

## Additional information
![Kapture 2022-01-06 at 03 41 49](https://user-images.githubusercontent.com/35540320/148314467-d30877bc-5fc8-4387-8206-cb5f06550c1a.gif)

**Comment by hirsch88** [comment]
@BerSteve Thanks for reporting this issue. Bug is fixed in version 9.1.0.
