### ISSUE TITLE
[bal-data][Mobile] Missing visual separation between Key/Values

### ISSUE THREAD

**Issue by Gagne87** [baloise/design-system#461]
**Steps to reproduce:** 

1. Go to [component](https://design.baloise.dev/?path=/docs/components-data--basic&globals=backgrounds.grid:true)
2. Change view to mobile in the browser (I used an iPhone SE) 

>> Between Key/Values there is only 8px in the moment which makes the visual separation for the user really hard. 
>> Expected behavior: Padding should be increased to 16px between Key/Values

![image](https://user-images.githubusercontent.com/29020214/148747006-5f310f62-c38a-4e8d-bc55-8c1798ac675a.png)

**Comment by hirsch88** [comment]
fixed in version 9.1.0
