### ISSUE TITLE
[Mobile][Modal] Wrong button order

### ISSUE THREAD

**Issue by Gagne87** [baloise/design-system#475]
**Testdevice:** Chrome / DevTools / iPhone SE

On mobile devices we have at the moment the wrong order of buttons (compare to screenshot). 

Expected behavior: The primary action comes first (in this case "Speichern") and then the secondary action underneath (in this case "Abbrechen")  

<img width="473" alt="Bildschirmfoto 2022-01-21 um 10 51 29" src="https://user-images.githubusercontent.com/29020214/150505722-986fc385-4fe9-4415-9b79-b658b790370f.png">

**Comment by hirsch88** [comment]
fixed in version 9.1.0
