### ISSUE TITLE
[Pagination][Mobile] Pagination breaks on small devices

### ISSUE THREAD

**Issue by Gagne87** [baloise/design-system#476]
**Testdevice:** Chrome / DevTools / iPhone SE

**Bug description:** On very small devices the pagination breaks in two lines. 
**Expected behavior:** If all buttons are not fitting in one row, then the first ones and the last one should be visible – in between there should be a placeholder "..."

<img width="597" alt="Bildschirmfoto 2022-01-21 um 10 56 16" src="https://user-images.githubusercontent.com/29020214/150506643-a7b91dc3-fa40-4f7b-b439-61e932fc6599.png">

**Comment by hirsch88** [comment]
fixed in version 9.1.0
