### ISSUE TITLE
[Mobile][bal-data] Spacing issues 

### ISSUE THREAD

**Issue by Gagne87** [baloise/design-system#477]
**Testdevice:** Chrome / DevTools / iPhone SE

**Bug description:** If the element converts into the mobile view, than following spacings don't have the right space anymore: 
- Space between label and input (-> should be the same as we use for our input elements) 
- Spacing between key/values too small (-> should be 16px)

Furthermore there are happening overflows if inputs are too long (compare to screenshot)

<img width="323" alt="Bildschirmfoto 2022-01-21 um 11 00 38" src="https://user-images.githubusercontent.com/29020214/150507279-123b70f6-8f7c-443a-ab64-a5f5cffff056.png">

**Comment by hirsch88** [comment]
fixed in version 9.1.0
