### ISSUE TITLE
[Component Request] - Counter 

### ISSUE THREAD

**Issue by Gagne87** [baloise/design-system#493]
As user of the household insurance calculator, I want to be able to add the number of rooms in my apartment via clicking + and -, that I don't have to use my keyboard. 

### Justification

This feature can be used in all insurance calculators in the group. 

### Desired UX and success metrics
The element should consist two icon only buttons and an input in between that cannot be edited. 

### Must-have functionality

The counter should start at 0 and max. allow 10 (considering half steps > 1 | 0, 1, 1.5, 2, 2.5, 3, 3.5, 4 etc.). Clicking on minus should reduce the number accordingly, clicking on plus should increase accordingly. 

### Specific timeline issues / requests
The feature needs to be developed within Feb 22'
![image](https://user-images.githubusercontent.com/29020214/152323165-0614a11e-c424-46a9-8a3c-1d4ecb71153a.png)

**Comment by hirsch88** [comment]
#517 517
