### ISSUE TITLE
`bal-select` component throwing `Element.querySelector: 'button#' is not a valid selector`

### ISSUE THREAD

**Issue by BerSteve** [baloise/design-system#511]
## Detailed description
We are getting this error from bugnsag
> SyntaxError · Element.querySelector: 'button#' is not a valid selector

which happens on various browsers/browser versions and devices. I cannot reproduce it myself, but this error pups up frequently.

My assumption would be that [here](https://github.com/baloise/design-system/blob/master/packages/components/src/components/form/bal-select/bal-select.tsx#L424) in some cases 
`option.id` is an empty string, which causes this error.
## Steps to reproduce the issue
Version used: `10.0.0`
Here are the user actions
<img width="789" alt="Screenshot 2022-02-15 at 15 13 47" src="https://user-images.githubusercontent.com/35540320/154069290-3a7b2d8a-50d4-4bb8-a9a0-e183c5679a4a.png">
<img width="951" alt="Screenshot 2022-02-15 at 15 21 11" src="https://user-images.githubusercontent.com/35540320/154070331-8168169b-725b-4f67-8f39-9450639b6b3b.png">

If you need any additional information please reach out.

**Comment by hirsch88** [comment]
Hi @BerSteve 
Will be fixed with 
https://github.com/baloise/design-system/pull/512/commits/1fc58d9e9ebd5cd586a96d9216592dbb56b7dd51
