### ISSUE TITLE
[React] - Can't resolve '@baloise/design-system-components/loader'

### ISSUE THREAD

**Issue by whvneo** [baloise/design-system#518]
## Detailed description

Followed the instructions on https://design.baloise.dev/?path=/story/getting-started-react-installation--page

## Steps to reproduce the issue

1. npx create-react-app bal-app --typescript
2. cd bal-app
3. npm install -D sass
4. Changed css to scss and als the imports in Index.tsx and App.tsx
5. npm install @baloise/design-system-components-react
6. npm install copyfiles --save-dev
7. npm run start

Compilation is not working:

```
Compiled with problems:

ERROR in ./node_modules/@baloise/design-system-components-react/dist/index.mjs 9:0-96

Module not found: Error: Can't resolve '@baloise/design-system-components/loader' in 'C:\Users\Public\dev\Projects\ReactJS\baloise-self-service\node_modules\@baloise\design-system-components-react\dist'
Did you mean 'index.js'?
BREAKING CHANGE: The request '@baloise/design-system-components/loader' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

## Additional information

- Affected Version 10.1.0
- create-react-app 17

**Comment by hirsch88** [comment]
@whvneo Thanks for reporting issue. It looks like that react is not able to understand .mjs files. I adjusted that and will be released soon.

In the meanwhile use this beta version with the fix and let me know if it works again.

@baloise/design-system-components-react@10.1.1-beta.6

**Comment by hirsch88** [comment]
PR is open => https://github.com/baloise/design-system/pull/519

**Comment by whvneo** [comment]
@hirsch88 
10.1.1-beta.6 is working fine. 
Thanks

**Comment by hirsch88** [comment]
@whvneo Version 10.2.0 released with the fix

https://github.com/baloise/design-system/blob/master/CHANGELOG.md#1020-2022-02-21
