### ISSUE TITLE
[React] - Button renders text outside of go back with browser

### ISSUE THREAD

**Issue by ThomasSeyssensTPO** [baloise/design-system#523]
### Detailed description
When using the button, on primary state, we encounter an issue.
![image](https://user-images.githubusercontent.com/83653862/155087001-06ff2234-a752-46c8-8a40-f00e7e421da8.png)

When inspecting the code, it seems like the text is not rendered on the desired place, but instead is added just after the opening tag instead of in the bal-text. It seems like the slot to render the button has a sort of delay. When refreshing the page, the button is rendered correctly.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/83653862/155087603-f4ae3e91-e48f-4565-bd7f-918c8173bbc5.png">

### Additional information
version used @baloise/design-system-components-react: 9.0.7

**Comment by hirsch88** [comment]
Hi @ThomasSeyssensTPO 

Thank you for reporting this issue. Could you also provide me the react code to reproduce this behaviour.

**Comment by ThomasSeyssensTPO** [comment]
Hi @hirsch88 ,

The code we use for implementing the button is the following:
```
{page.nextPage !== undefined && (
        <BalButton
            className="lg-next"
            color={page.buttons.next.type}
            disabled={isNextButtonDisabled}
            href={
                page.isNextPageExternal ? page.nextPage : undefined
            }
            onClick={
                nextPage
                    ? () => {
                          nextAction();
                      }
                    : undefined
            }
            icon={
                page.buttons.next.icon
                    ? page.buttons.next.icon
                    : undefined
            }
            iconRight={
                page.buttons.next.iconRight
                    ? page.buttons.next.iconRight
                    : undefined
            }
        >
            {t(page?.buttons.next.text)}
        </BalButton>
    )}```

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/pull/526

mark react as experimental

**Comment by ThomasSeyssensTPO** [comment]
The issue appears when a direct react change (translation function, conditional text without wrapper, ... ) is set directly inside a slotted component. React will try to replace the function on the first element it's wrapped in, but since the button in this case renders with multiple children, the buttontext will be rendered on the wrong place.

### Fix for this issue
Add a react fragment (React.Fragment or <></>) around the conditional content, which will give React the opportunity to replace on the fragment instead of the stencil component.
