### ISSUE TITLE
Different format for Datepicker, month and year only view

### ISSUE THREAD

**Issue by whvneo** [baloise/design-system#525]
### Summary

In our application VEAS we use the datepicker with success. For some fields we only need the year or the month of a date.

### Justification

To use different formats of the rendered date makes it easier for the developer to use this component and for the user the datepicker layout would be easier to use when it is only possible to use month or year.

When a "month" view is used, it should return a regular Date, saying the first of the selected month and the same for "year". There it should return the first of the year.

This "min" and "max" can be used as well

#### Month

In this view the user only can select a month, so it is not necessary to show the dates.

#### Year

In this view the user only can select a year, so it is not necessary to show the dates and months.

### Must-have functionality

Parameter to switch between these three views (date, month, year)

### Specific timeline issues / requests

No special timeline, we have a workaround currently

### Available extra resources

Testing myself is pssible

**Comment by hirsch88** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Different format for Datepicker, month and year only view](https://trello.com/c/QPIMNi0h/11-different-format-for-datepicker-month-and-year-only-view)
