### ISSUE TITLE
New Icon: Logout

### ISSUE THREAD

**Issue by whvneo** [baloise/design-system#528]
### Summary

In our application we would like to have a logout button and need therefor an icon.

### Justification

For an application not using SSO it is necessary to have a logout button and for this we need an icon. Of course we could use one of fontawesome or something else but having an icon available makes the UI more consistent. It also makes licensing questions from third party icon packages easier beacuse we don't use them.

### Desired UX and success metrics

Logout icon showing a user logging out

### Must-have functionality

Icon must be available

### Specific timeline issues / requests

Workaround in place (using "power.off" icon from fontawesome.

### Available extra resources

See the [Fontawesome Page](https://fontawesome.com/search?q=poweroff&s=solid%2Cbrands) for inspiration

**Comment by Gagne87** [comment]
I would suggest, that we use following icon for it: 
![streamline-icon-interface-logout-square-alternate@48x48](https://user-images.githubusercontent.com/29020214/156140949-e97e271c-56c0-44bf-b0d7-dc398886b568.svg)

**Comment by hirsch88** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [asfd](https://trello.com/c/82js1NCE/12-asfd)

**Comment by whvneo** [comment]
Agreed

**Comment by hirsch88** [comment]
icon is added
