### ISSUE TITLE
Datepicker dates and days of week do not align

### ISSUE THREAD

**Issue by BerSteve** [baloise/design-system#535]
## Detailed description

> Describe in detail the issue you're having.

Datepicker dates and days of week do not align - 02.03.2022 should be `Wednesday`, but currently its displayed as `Thursday`  

> What did you expect to happen? What happened instead? What would you like to see changed?

Correctly display dates and days of week

## Steps to reproduce the issue
From storybook 
https://design.baloise.dev/?path=/story/components-form-datepicker--basic
## Additional information
![Screenshot 2022-03-02 at 16 22 13](https://user-images.githubusercontent.com/35540320/156379974-6fc57e5d-6655-475d-bb13-143365ca39d0.png)
![Screenshot 2022-03-02 at 16 27 39](https://user-images.githubusercontent.com/35540320/156380933-6c47edad-2d6b-484e-bd05-f2391a5dbbe2.png)

**Comment by hirsch88** [comment]
Hi @BerSteve 
Thank you for reporting this issue. Created a PR with the fix. 
https://github.com/baloise/design-system/pull/545
