### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by sambeauvois** [baloise/design-system#536]
### Summary

Could you add the favicons to the design system ?

### Justification

It would be easier to find them and to add them into new applications

### Desired UX and success metrics

As a developper, I'd like a section where I can downoad the favicons in all formats (.ico file, but also for different devices)

It would be nice to have the code to add them so we can just copy/paste it to our applications

ex :
```
<link rel="apple-touch-icon" sizes="180x180" href="assets/images/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon/favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="assets/images/favicon/favicon-32x32.png">
```

### Must-have functionality

Find the favicons easily

### Specific timeline issues / requests

/

### Available extra resources

They are used in the "https://design.baloise.dev/" website

**Comment by hirsch88** [comment]
moved issue
