### ISSUE TITLE
[Checkbox][Radio] Alignment breaks on Safari and iOS

### ISSUE THREAD

**Issue by Gagne87** [baloise/design-system#549]
On Safari and iOS we found a bug that the labels are not aligned anymore to the rectangle (checkbox) or the ellipse (radio). Please compare to the screenshot. 

## Steps to reproduce the issue

1. Open the Checkbox or Radio on Safari (I am using Safari in Version 15.3 (17612.4.9.1.8))

<img width="497" alt="image" src="https://user-images.githubusercontent.com/29020214/157443242-5b769ae9-5f95-4d1f-bfab-d2df638b01e2.png">

**Comment by hirsch88** [comment]
wont do
