### ISSUE TITLE
Component aliases for legacy components

### ISSUE THREAD

**Issue by Flapmax** [baloise/design-system#560]
### Summary

As we currently create new components and replace old ones, some components become irrelevant. It would be nice to have the possibility to support old components for a certain amount of time. They could for example still be used in old projects but not in new ones. Teams would have to upgrade after a certain amount of time.

This would not be possible in FIGMA but can certainly be an option for developers.

### Justification

This way we can optimise and reduce the number of components without breaking current projects and products.

#### Features

- The Design System automatically recognises where old components are still used.
- Components can have aliases - the system recognises an old name and automatically links to a newer component.
- General usage statistics would be interesting to get an idea of the scope of a change.

**Comment by hirsch88** [comment]
Will do that on specific cases
