### ISSUE TITLE
[suggestion] Register your namespace "bal"

### ISSUE THREAD

**Issue by nuxodin** [baloise/design-system#569]
### Summary

There are already many design systems.
To avoid naming collisions, there is a project:
https://github.com/nuxodin/web-namespace-registry

Maybe you want to register the namespace "bal" here with a pull request?

**Comment by hirsch88** [comment]
@nuxodin 

Done :-)

https://github.com/nuxodin/web-namespace-registry/pull/18

**Comment by nuxodin** [comment]
great!
