### ISSUE TITLE
[Datepicker] Display different date formats for countries

### ISSUE THREAD

**Issue by Gagne87** [baloise/design-system#574]
As baloise.ch user in Belgium, I want to see the date in my local format, so that I don't even have to think about it. 

### Summary

Following date formats should be implemented: 

- **Belgium:** DD/MM/YYYY (e.g. 24/06/1999)
- **Luxembourg:** DD/MM/YYYY (e.g. 24/06/1999)

**Note:** The date format is not language sensitive.

**Comment by hirsch88** [comment]
is done in version 1.8.3
