### ISSUE TITLE
Slider Component

### ISSUE THREAD

**Issue by ThomasSeyssensTPO** [baloise/design-system#602]
## Slider component background width calculation is off

> When giving the Slider component a max value of 20000, the calculation of the background-styles are getting calculated depending on the step-size, e.g. when the step is 5000, the percentage of the bg is 5000%.
<img width="389" alt="image" src="https://user-images.githubusercontent.com/83653862/165076732-9e2430a9-ed33-4473-8c48-ddad402f0791.png">

> Also, the ticks on the slider are not available. The flag hasTicks is used, but does nothing.

> Working in chrome on macOs

## Steps to reproduce the issue

1. Add a BalSlider component
2. Add a max value of 20.000
3. Add a step value of 5.000
4. Run page and select a value.

## Additional information

- Screenshots or code
- Notes

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/pull/603
