### ISSUE TITLE
Bal-Tag with a bal-card

### ISSUE THREAD

**Issue by sambeauvois** [baloise/design-system#609]
## Detailed description

> I added a bal-tag in a bal-card component.

> I was expecting to have the tag applied to the card, but instead it was applied to the first bal-card of the page

> chrome and edge 

## Steps to reproduce the issue

1. add several bal-card to a page
2. add a bal-tag to one of them (not the first one)
3. check the page

## Additional information

- Screenshots or code
- 
![image](https://user-images.githubusercontent.com/141645/167116935-d77996c9-65e3-481e-a980-0cab5ea656bb.png)

- Notes

**Comment by mladenplaninicic** [comment]
Hello @sambeauvois 

the bug is fixed in version 10.11.1

Tnx for reporting.
