### ISSUE TITLE
Adjusting bal-select to meet the requirements of SoBa

### ISSUE THREAD

**Issue by jacnguymesoneer** [baloise/design-system#610]
### Summary

The SoBa DEV-team (mesonner, previousely UMB) would like to request three changes for the component bal-select in order to support the requirements of SoBa regarding this component and also to improve it.

### Justification

Our DEV-Team requests three following changes because otherwise, we have to keep using a customized bal-select component in order to meet the requirements/expectations of SoBa regarding the dropdown component:

- Customized filter functionality:
The does not support customized filter functionality. For example, it only supports filtering out options which includes/contains the entered words (e.g. when user enters a word, it will show all the options which contain the entered word regardles of the position).

- minQueryLength:
If the dropdown list has too many options, e.g. 4'000 options, then it could lead to performance issues loading all of the dropdown items. Currently, we customized our dropdown component in SOB and start the query beginning with the second letter instead starting with the first one.

- Autocapitalize:
Currently, if user types in word e.g. "schweiz" in lowercase and it is part of the dropdown, it will use that value instead of taking over the exact value from the dropdown with first letter being uppercase "Schweiz".
However, since the user types in schweiz in lowercase, it will therefore use this value. Would it be possible to have an autocapitalize behavior, so when user types in schweiz for example, bal-select will check for upper/lowercase of the dropdown list items and use that one if value equals one of the options? schweiz --> Schweiz

### Desired UX and success metrics

- Customized filter functionality:
Filtering options by only considering the exact positioning as the entered word. If user types in "Testing", it should display options which starts exactly with "Testing" and not display any option which does not start with "Testing" like "SOB Testing"
Filtering options by additional field (additional lookup value, neither label nor value, e.g. please check for screenshot, where 0041 was typed in instead of +41).

- minQueryLength:
Is it possible to introduce an option for bal-select to set a minQueryLength so that it starts loading/searching for the items in the dropdown according to the defined minimum required characters?

- Autocapitalize:
Would it be possible to support the autocapitalization of the first letter? Let's say, user enters schweiz and it is part of the dropdown values. Therefore, this value will be used but with the first letter being uppercase e.g. "Schweiz". Either autocapitalize or automatically use the dropdown item (Schweiz). Currently, it will treat "schweiz" as valid and user can continue.

### Specific timeline issues / requests

If possible, please adjust the bal-select component before the Rebranding.

**Comment by hirsch88** [comment]
moved issue
