### ISSUE TITLE
Vue3 kebab-case events.

### ISSUE THREAD

**Issue by abe-modyo** [baloise/design-system#613]
hello! I hope you are well!

how did you solve the problem of vue3 with the events in camelCase from stencil https://github.com/ionic-team/stencil/issues/2804?

I'm trying not to use `defineCustomElements` and trying to implement a solution similar to ionic framework https://github.com/ionic-team/ionic-framework/commit/dc48a9f1a2dff8a2d644112bbe1df8b0b6811848#diff-8cee275a9cf24f29120acc6b18432e1b43901e53e260a64bd180c97a64bd180

but, my helpers never run.

**Comment by hirsch88** [comment]
@abe-modyo hi we are using our own output generator => https://github.com/baloise/stencil-ds-output-targets
hope that helps with your issue
