### ISSUE TITLE
Navbar - navbar brand - specify linked page

### ISSUE THREAD

**Issue by sambeauvois** [baloise/design-system#615]
### Summary

Would it be possible to specify the page linked by the application logo

Clarify if you are asking for both design and development, or just design, or just development. **---> Just development**

### Justification

I have several "apps" living in the same project, hosted on the same server, with the same base url
ex: tarif.baloise.lu/goodstartlocataire, tarif.baloise.lu/ipension
So I want the logo to target the "home page" of the related application

### Desired UX and success metrics

If an user clicks on the home logo, he is redirected to the home page of the application (not the root of the server)

### Must-have functionality

/

### Specific timeline issues / requests

/

### Available extra resources

/

**Comment by hirsch88** [comment]
<img width="974" alt="image" src="https://user-images.githubusercontent.com/6384499/171988107-5aaf4fa8-d5c7-47e4-9b64-c4cdb858d2cf.png">

@sambeauvois did you try to set href on the the navbar-brand component?

**Comment by sambeauvois** [comment]
Hi, I missed this part in the doc, sorry
It's working :)
