### ISSUE TITLE
Datepicker - Months not updated when navigating backwards

### ISSUE THREAD

**Issue by jacnguymesoneer** [baloise/design-system#618]
## Detailed description

Currently, we are using the datepicker component for the SOB of SoBa (banking.baloise.ch). In the second page, the component can be accessed and whenever the user tries to navigate backwards, it the month will not get updated automatically. It will still display e.g. May for example instead of April. 

However, the forward navigations do not have this issue and the month will get updated from May --> June for example.

This issue can be observed on the SoBa site: www.banking.baloise.ch

## Steps to reproduce the issue

1. Go to second page
2. Navigate to datepicker field and open it via mouse click
3. Navigate backwards by clicking on "<"
4. It can be observed that description of the month in the header of this component does not get updated
5. Screenshot will display that the month is changed to April (30 days) but the month title is still May

![image](https://user-images.githubusercontent.com/104895699/169811559-d8f9155e-ce10-4c36-8f7a-57b49a76ada6.png)
![image](https://user-images.githubusercontent.com/104895699/169811702-8bd81e8f-d301-49d3-afac-5a0d64907fcc.png)

**Comment by hirsch88** [comment]
moved issue
