### ISSUE TITLE
Claim Number Input is not accepting check number X

### ISSUE THREAD

**Issue by chester23491** [baloise/design-system#632]
## Claim Number Input validation is not accepting claims number ending with X.

The check number in the claim number format is not accepted by the mask `"claim-number"` in `bal-input`.
E.g. the claim number `4400000321X` is not accepted by the mask.

## Steps to reproduce the issue

1. Goto the website: https://design.baloise.dev/?path=/story/components-form-input--claim-number-input
2. Enter `4400000321X`
3. **X is not accepted**

**Comment by hirsch88** [comment]
@nobilo and @Gagne87 could you have a look at this issue?

**Comment by nobilo** [comment]
We have clarified requirements so one option for claim number is:
44/123456/21.X 
so the last character is:  `0-9 or X`
