### ISSUE TITLE
Adding release notes to Slack

### ISSUE THREAD

**Issue by clastzoo** [baloise/design-system#640]
### Summary

To be up-to-date about the newest design system release, we would like to add this information to the Slack channels:

```
- design-system-focus 
- rebranding-ext
```

### Justification

Alignment between different teams, stakeholders.

### Must-have functionality

- Newest Changelog in Slack

### Specific timeline issues / requests

- When ever the time is ready – but as latest **end of July**

### Available extra resources

Channel ID

```
- design-system-focus Channel ID: C02QQ4TTKRB
- rebranding-ext Channel ID: C02P8SA1Y2D
```

Maybe helpful – https://github.com/integrations/slack/issues/397

**Comment by hirsch88** [comment]
done
