### ISSUE TITLE
bal-select has no fallback to react for form reset 

### ISSUE THREAD

**Issue by Sw0rdiX** [baloise/design-system#641]
## Detailed description

> Describe in detail the issue you're having.
- If u reset a Form, the default value for bal-select will not be selected anymore...

> What did you expect to happen? What happened instead? What would you like to see changed?
- If i reset a Form, the value which is put in the bal-select as selected value will be selected again. 

> What browser are you working in?
- Chrome

## Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/3681337/177402590-1f70f160-8111-4b9a-a911-7fbed9eac52c.png)

1. select another value as selected
2. reset form 

## Additional information

- Screenshots of Working Code
![image](https://user-images.githubusercontent.com/3681337/177402395-5676b550-1712-4ece-82dd-4255ae786b63.png)

**Comment by hirsch88** [comment]
Moved issue
