### ISSUE TITLE
Value accessor for bal-file-upload

### ISSUE THREAD

**Issue by predrag-arsic** [baloise/design-system#653]
At the moment we dont have value accessor for this component, so we were forced to override the value of the component and create workaround with it.

The use case where we need it is when the form has few steps(a wizard), and when the user leaves the page where the bal-file-upload is, after he's back, none of the files is shown to him. As said, for current purpose, this behaviour is overridden, but would need the accessor for these cases.

**Comment by nobilo** [comment]
https://github.com/baloise-incubator/design-system/issues/412
