### ISSUE TITLE
[Documentation] : The documentation website is down

### ISSUE THREAD

**Issue by remi-martinez** [baloise/design-system#657]
## Detailed description

The documentation website (Storybook) is currently down, with a 503 (Service unavailable) error.

## Steps to reproduce the issue

1. Log onto `https://design.baloise.dev/`

## Additional information

Using Chrome 105.0.5195.127

**Screenshot :  **
![image](https://user-images.githubusercontent.com/64494563/190877275-29ed83bd-f2eb-45a9-8769-8e420640c25d.png)

**Comment by chester23491** [comment]
Same issue here. My current workaround is to run the documentation locally.

```
npm install
npm run storybook
npm run storybook:start
```

Open the documentation locally `http://127.0.0.1:8080`.

Good luck!

**Comment by hirsch88** [comment]
use this link for now => https://baloise-design.vercel.app/?path=/story/welcome--page
