### ISSUE TITLE
[bal-navbar-brand] fix control target

### ISSUE THREAD

**Issue by NoraKurzbein** [baloise/design-system#659]
## Detailed description

We use <bal-navbar-brand> component in header we want to use it as a link, but it's not possible to open the link in the same tab. Target is somehow set to target="_blank". We would like to pass the target value as an attribut and set it to  target="_self"

## Steps to reproduce the issue

1. Use <bal-navbar-brand> set href-Attribute, set target-Attribute
2. Open webpage and click on it 
3. It will open a new tab even if you set target to "_self"
4. etc.

## Additional information

Thank you!

**Comment by hirsch88** [comment]
transfered to => https://github.com/baloise-incubator/design-system/issues/769
