### ISSUE TITLE
Mobile Navbar Menu scrollable 

### ISSUE THREAD

**Issue by yannickholzenkamp** [baloise/design-system#660]
## Detailed description

The area of the mobile navbar header is scrollable when navigation open on mobile 

## Steps to reproduce the issue

1. Have a page with navbar and navbar content
2. Add page content larger than the screen size
3. Open the navbar on mobile 
4. Scroll on mobile

Now the navbar disappears (scrolls down) and in the area where the top navbar was, the page content appears as you scroll.

## Additional information

<img width="338" alt="Bildschirmfoto 2022-10-18 um 13 40 19" src="https://user-images.githubusercontent.com/9351023/196419911-908d7649-5f6b-4812-9477-e42692d723df.png">

**Comment by hirsch88** [comment]
transfered to => https://github.com/baloise-incubator/design-system/issues/770
