### ISSUE TITLE
Control the 'x' of <bal-modal>

### ISSUE THREAD

**Issue by NoraKurzbein** [baloise/design-system#661]
If I use the <bal-modal> component, I would like to control the beahvior. So for example if pressing the 'x' would emit an event.

Example Use Case is 'Terms of Use' if a user logs in and there is a new Terms of Use we show it, if one clicks on the 'x' the modal closes and you stay on the overview page you end up in an endless loop. I would like to redirect to logout page in this case, but thats not possible.

**Comment by nobilo** [comment]
Should the click on `x` behave the same as cancel button so it emits the event?
