### ISSUE TITLE
Fields in background are still selectable if modal dialog is shown

### ISSUE THREAD

**Issue by baengel** [baloise/design-system#663]
## Detailed description

> If you are opening a modal dialog, the button or fields in the background are still selectable with the tab key.

> the fields in the background shouldn't be selectable.

> chrome

## Steps to reproduce the issue

1. go to https://baloise-design.vercel.app/?path=/story/components-notice-modal--with-input
2. click on "Trigger a modal" button
3. If you go with tab trough fields (or shift + tab) then you can still select the button in the background

## Additional information
![image](https://user-images.githubusercontent.com/12473997/197533564-bde94e7b-bf52-408f-a02b-83a859bc9691.png)

in mybaloise-business it's possible to open the same dialog several times.

**Comment by nobilo** [comment]
https://github.com/baloise-incubator/design-system/issues/803
