### ISSUE TITLE
Checkboxes in AG-Grid need more contrast

### ISSUE THREAD

**Issue by Tiliavir** [baloise/design-system#668]
After updating our application to the rebranded versions, users complained that they can't see checkboxes very well in the ag-grid.

![image](https://user-images.githubusercontent.com/8123039/204474821-e14748c2-45c4-43a6-b964-eaf8276fad88.png)
https://baloise-design-system.vercel.app/?path=/story/components-table--ag-grid

**Comment by hirsch88** [comment]
Hi @Tiliavir will be done in that task
https://github.com/baloise-incubator/design-system/issues/979
