### ISSUE TITLE
It isn't possible to input correct decimal numbers, if the bal-number-input tag is used with german settings

### ISSUE THREAD

**Issue by VeniaminAvakovBaloise** [baloise/design-system#669]
## Detailed description

If the _bal-number-input_ tag is used with german settings and we try to input a decimal number e.g. **1234,56**, then the input field shows **1234,00**.

## Steps to reproduce the issue

1. Use german settings for the baloise component system configuration: 
- Region: de
- Language: DE
2. Declare the _bal-number-input_ field
4. Try to input: **1234,56**
5. The input field shows: **1234,00**

## Additional information

![image](https://user-images.githubusercontent.com/119490777/204786367-d9dfd102-4f2f-4934-99ff-1654aa3b5144.png)

**Comment by hirsch88** [comment]
Hi @VeniaminAvakovBaloise will be done in that task
https://github.com/baloise-incubator/design-system/issues/978
