### ISSUE TITLE
:sparkles: feat(tabs): allow overflow & add scroll to centre for selected tab

### ISSUE THREAD

**Issue by WouterBridtsMS** [baloise/design-system#678]
### Summary

Add a 'scroll to center effect' tot mobile tabs to improve the user experience and indicate whether there are more tabs which were not visible due to the limited screen size.
Using the existing design, adding extra behaviour through development.

### Use Case

A higher number of tabs (>4) is not the exception. Working in a complex environment of insurances, the use of multiple tabs is often requited. Currentky, it is hard for the user to notice if there are more tabs available. We can improve the findability of these tabs on mobile screens by implementing an extra scroll interaction. Using this, the next and previous tab will always be (at least partly) visible.

### Preferred Solution

Desired UX, see [Figma](https://www.figma.com/file/rCT8571RRVLf1xh4vpk2Ak/Raised-issues%2Fimprovements?node-id=101%3A9099&t=ZriffBWB0WDPZrlH-1)

Success metrics: improved use of otherwise less visible tabs.

### Additional Information

The first screens with less visible tabs will go live soon. The faster this improvement can be added to the design system, the faster our end-users will benefit from this.

From the Belgian Design Center of Excellence, we are available to further finetune the design and behaviour.

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
@StefaanSaeys With the new implementation of the tabs and the overflow solution we will not implement the scroll to the middle.

**Comment by WouterBridtsMS** [comment]
Hi @hirsch88, can we see the new tabs implementation and overflow solution somewhere? Or when will the new tabs be released?
