### ISSUE TITLE
:sparkles: feat(form): add clear function

### ISSUE THREAD

**Issue by hirsch88** [baloise/design-system#698]
### Summary

Acceptance criteria: 

- [ ] Find a way to place a button/icon in input fields in order that the user can delete inputs in a bulk
- [ ] Implement solution

### Use Case

As user, I want to be able to delete my input in the search field with one click, so that I save time on deleting every single character. See example attached to this ticket.

### Additional Information

![Image](https://user-images.githubusercontent.com/29020214/199977223-946b3bbf-a816-4ef0-87b3-4de8fc881489.png)

Figma example can be found [here](https://www.figma.com/file/lgDn2QZqoJJlYzGTe6cOmr/%F0%9F%A7%A9-Components?node-id=1696%3A9575)

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Feamusbal** [comment]
Figma suggestion: 
https://www.figma.com/file/H2IcPK1nDHEcUoVUdOgQ47/%F0%9F%A7%AA-DS-Lab-%E2%80%93-Explore-your-ideas?type=design&node-id=507-40138&mode=design&t=1kwE7hwm10sLzClI-0

**Comment by Feamusbal** [comment]
Designs which were discussed in July 2023: https://www.figma.com/file/H2IcPK1nDHEcUoVUdOgQ47/%F0%9F%A7%AA-DS-Lab-%E2%80%93-Explore-your-ideas?type=design&node-id=507-40138&mode=design&t=1u2XyC47i2pOnFIS-0

**Comment by hirsch88** [comment]
We close this issue due to inactivity
