### ISSUE TITLE
:bug: fix(radio checkbox): multiline solutions

### ISSUE THREAD

**Issue by hirsch88** [baloise/design-system#705]
### Current Behavior

with multi-line labels in a select button (<bal-radio-group interface="select-button" ... ) the circle indicator is not shown in the middle. Also, in a group of radio buttons, the height should align with the highest element (i.e. expand the smaller ones).

### Expected Behavior

- [ ] on mobile the have 100% width
- [ ] should allow multiline labels and wrap the text and the other option should have the same height and be centered 

### Steps to Reproduce

1. on option with a long label

### Version

12

### Additional Information

![image](https://user-images.githubusercontent.com/292344/204571922-04c66442-616b-4d70-88e4-45a9a819b348.png)

As a workaround, we overwrite the styling in our app with the following attributes. (As a help)
```
::ng-deep {
  .package-selection {
    .bal-radio-checkbox {
      min-height: 4rem;
    }

    .bal-radio-checkbox__label::before, .bal-radio-checkbox__label::after {
      top: inherit;
    }
  }
}
```

created by @tk

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mladenplaninicic** [comment]
this issue is already fixed.
