### ISSUE TITLE
:wrench: chore: add contributors to new org

### ISSUE THREAD

**Issue by hirsch88** [baloise/design-system#707]
### Summary

- [x] baengel
- [x] BerSteve
- [x] Feamusbal
- [x] jacnguymesoneer 
- [x] petramohler
- [x] StefaanSaeys

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Waiting for the PR to be approved and merged

https://github.com/baloise/org/pull/57

**Comment by hirsch88** [comment]
@joachimprinzbach could you approve the [PR](https://github.com/baloise/org/pull/57)

**Comment by hirsch88** [comment]
@joachimprinzbach new pr https://github.com/baloise/org/pull/59
Please have a look

**Comment by joachimprinzbach** [comment]
@hirsch88 accepted, you should be able to merge

**Comment by hirsch88** [comment]
@joachimprinzbach thank you
