### ISSUE TITLE
:wrench: chore: fix open-shift documentation deployment

### ISSUE THREAD

**Issue by hirsch88** [baloise/design-system#783]
### Summary

We finally fixed the docker build with turbo. See [documentation action log](https://github.com/baloise/design-system/actions/runs/4751724251/jobs/8441192650
).

Also the upload to open-shift looks good to us, but the deployment did not work for https://design.baloise.dev.

@joachimprinzbach could you please check why I did not deploy completely.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joachimprinzbach** [comment]
Looks like a DNS issue, I asked @niiku for assistance as I do not have access to the DNS settings

**Comment by joachimprinzbach** [comment]
According to the logs it should have been created: https://argocd.baloise.dev/applications/argocd/external-dns?view=tree&node=apps%2FDeployment%2Fexternal-dns%2Fexternal-dns%2F0&tab=logs

**Comment by hirsch88** [comment]
@joachimprinzbach thanks for you help. it works :-)
