### ISSUE TITLE
:sparkles: feat(card): add hover, pressed, focused and selected state

### ISSUE THREAD

**Issue by hirsch88** [baloise/design-system#788]
### Summary

The current card has no active state indictation, we have to add a border for an active card.

### Use Case

As a User I like to see my selected card

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
1. Have a look at the shadow levels if there are enough - done
2. Collect various clickable cards of apps/website
3. Identify a pattern

**Comment by lrommerskirchen** [comment]
@clastzoo I'll work on this due to our current project on the documents overview and based on our prio in Notion

**Comment by hirsch88** [comment]
We close this issue due to inactivity
