### ISSUE TITLE
:sparkles: feat(nationality-select): new form field component

### ISSUE THREAD

**Issue by Feamusbal** [baloise/design-system#810]
### Summary

The nationality form field is needed for most calculators as the nationality affects the insurance costs. Currently different teams are using different designs and different backend approaches (API vs. using own lists) to design the form field. 

The nationality form field should:

- Be based on the "Select" component 
- Be a search/filter dropdown 
- show the countries in alphabetical order in all languages (DE,FR,IT,EN) 
- The most common countries should be shown at the top of the list (CH, IT, DE, PT, FR) 
- Show the countries flag as additional help for the users.
- consider Switzerland as a default answer (however, it should remain easy to switch countries)

-The current MF calculator meets most requirements, but the list can't be searched: https://www.baloise.ch/de/privatkunden/versichern/fahrzeuge/autoversicherung/praemie-berechnen.html?channel=baloise#/qnb-flow/mfp-relevant-data
-The list used for Bank Now is searchable, but does not show the countries in the right order and most common countries are not at the top of the list: https://acc-www.baloise.ch/banknow/car-search

![Current MF calculator](https://user-images.githubusercontent.com/112086425/234810318-032f580b-8d41-4ab6-99ff-f70e201a5683.JPG)

![Bank Now](https://user-images.githubusercontent.com/112086425/234810238-941325f1-32bf-4222-89f9-c99381a3e8f8.JPG)

### Use Case

Currently it is a problem for the standalone solution for Bank Now / Ford. Here the issue is not quite as bad as only expert users will use the application. 

However, all calculators which use the nationality field will be affected at some point 

### Preferred Solution

The nationality form field should:

Be based on "Select" component
Be a search/filter dropdown
show the countries in alphabetical order in all languages (DE,FR,IT,EN)
Show the countries flag as additional help for the users.
The most common countries should be shown at the top of the list (CH, IT, DE, PT, FR)
consider Switzerland as a default answer (however, it should remain easy to switch countries)

### Additional Information

Discussed in the weekly UX sync on 25/4. Happy to help to create the design. 

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
We close this issue due to inactivity
