### ISSUE TITLE
:sparkles: feat(component): Postcode form fields

### ISSUE THREAD

**Issue by Feamusbal** [baloise/design-system#811]
### Summary

The postal code form field is needed for most calculators as it is needed to know where customers live. Currently different teams are using different design approaches. 

It is possible that a city has multiple postcodes (e.g., Basel has 4055, 4056, 4057 etc.) or that a postcode includes multiple villages (e.g., 1041 includes Dammartin, Montaubion-)Chardon, Naz, Poliez-le-Grand etc.)

The postcode form component should:

- there be only one option for the postcode the city field shows the city name 
-there be multiple villages with the same postcode, users must choose the village and there is a hint in the field

-For bank now we are using the two field approach: https://acc-www.baloise.ch/banknow/car-search
![Ban Now two fields](https://user-images.githubusercontent.com/112086425/234819012-5aac1c9c-83fd-42db-a0a5-4db0bfcf6c9c.JPG)

### Use Case

Needed for any application which asks customers for their address in Switzerland, e.g., Ford standalone solution. 

### Preferred Solution

The postcode form component should:

- there be only one option for the postcode the city field shows the city name 
-there be multiple villages with the same postcode, users must choose the village and there is a hint in the field

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
We close this issue due to inactivity
