### ISSUE TITLE
:bug: fix(button): certain icons not rendering

### ISSUE THREAD

**Issue by JasperDeLanghe** [baloise/design-system#814]
### Current Behavior

The `arrows-round-left` is not showing up as a button icon.
```jsx
<BalButton
    color="link"
    iconRight="arrows-round-left"
>
    tabs.reset
</BalButton>
```
![image](https://user-images.githubusercontent.com/25288931/235607109-3952a641-0a61-409d-a882-37f16f31b2e6.png)

While the `plus` icon does show up.
```jsx
<BalButton
    color="link"
    iconRight="plus"
>
    tabs.reset
</BalButton>
```
![image](https://user-images.githubusercontent.com/25288931/235607292-401f54f0-61c3-4f01-8419-ad1698d23c8b.png)

### Expected Behavior

All possible icons to be rendered

### Steps to Reproduce

1. create button component
2. add icon-right property with value `arrow-round-left`

### Version

12.13.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
@JasperDeLanghe Did you provide the icon `arrows-round-left` ?
