### ISSUE TITLE
:bug: fix(bal-accordion): label ngrx-translate

### ISSUE THREAD

**Issue by frevers81** [baloise/design-system#844]
### Current Behavior

I can't set the label text when using ngrx-translate. Attributes "open-label" and "close-label"

### Expected Behavior

same behavior as in the old version accordion

### Steps to Reproduce

1. set on bal-accordion-trigger attributes open-label or close-label with trasnlate pipe (         <bal-accordion-trigger button
                               open-icon="edit"
                               open-label="{{questionsGroup.accordionOpenLabelKey! | translate}}"
                               close-label="{{questionsGroup.accordionCloseLabelKey! | translate}}"
                               close-icon="close"></bal-accordion-trigger>)
2. only the icon is shown on accordion button.

![oldVersion](https://github.com/baloise/design-system/assets/107101038/234af899-8602-47b7-8c6f-c577c0cc34f9)
![newVersion](https://github.com/baloise/design-system/assets/107101038/8b8b6683-2467-4e63-b66e-e50cf209e9d2)

### Version

13.0.0

### Browsers

Chrome, Microsoft Edge

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
hi @frevers81 

You have to use it as a Angular property:

```html
<bal-accordion-trigger button open-icon="edit" [openLabel]="'title' | translate"></bal-accordion-trigger>
```

With your solution it is added once, but with that Angular property it will update when changed.
