### ISSUE TITLE
🐛 fix(tabs):  position indicator line stretches with content

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#880]
### Current Behavior

Currently the decorative line under or next to the tab navigation stretches with the content height / width.

<img width="865" alt="Bildschirmfoto 2023-05-16 um 15 34 40" src="https://github.com/baloise/design-system/assets/72393447/d8fa2d94-db6a-47b3-8e7b-c5bf6f4ab399">

### Expected Behavior

Per design it should only cover the length of the navigation items

### Steps to Reproduce

Default tabs usage

### Version

13.2.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
will be done by #879
