### ISSUE TITLE
🐛 fix(list): Icon and Content / Title not aligned

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#882]
### Current Behavior

Currently the icon and list title are not aligned horizontally. The title is slightly lower.

![image](https://github.com/baloise/design-system/assets/72393447/dee6d14b-5109-4246-aef9-0f1bc0947fe1)

### Expected Behavior

Title and Icon should be aligned in the middle

### Steps to Reproduce

regular list usage

### Version

13.2.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
issue on the website
