### ISSUE TITLE
:bug: fix(Magnolia login): Cypress clicks are not working with magnolia login buttons

### ISSUE THREAD

**Issue by didlika** [baloise/design-system#883]
### Current Behavior

When trying to login, click is not recognised and tests fail.

Here are screenshoots of the test and the method being used. 
![Screenshot 2023-05-19 at 11 12 33](https://github.com/baloise/design-system/assets/80490488/016a6e11-b94d-49f7-a2ea-c6276310d631)
![Screenshot 2023-05-19 at 11 15 09](https://github.com/baloise/design-system/assets/80490488/08b5b6e3-c501-4ce6-9a54-129086941f06)

### Expected Behavior

WIth older version of DS it was working.

### Steps to Reproduce

Click with cypress on login button.

### Version

13.3.0

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Device

Mobile, Tablet, Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
@didlika your apps are using v12 an higher, but the login is quite old and their for the selectors are not there. So please use a normal get(.button) what ever to find the submit button to click it
