### ISSUE TITLE
Improve documentation: migration to v12 missing examples and migration to v13 additional info for tabs

### ISSUE THREAD

**Issue by nobilo** [baloise/design-system#884]
### Question

Hey guys, one suggestion, i think it would make sense to update migration guide on v13 that now we have new component bal-stack and that tabs and steps need to be put inside it in order not to have this ugly arrows for left and right even though it fits on the screen :disappointed:. For example if you go here arrows are already there:
https://design.baloise.dev/?path=/story/components-navigation-steps--basic. Should i open an issue and what do you think about it ?
Also seems like examples are again missing in migration to v12: https://design.baloise.dev/?path=/docs/development-upgrade-guides-updating-to-v12--page (edited) 

### Additional Information

Go to canvas of  components-navigation-steps--basic, use size of preview to **large desktop** and it should be something like this:
![image](https://github.com/baloise/design-system/assets/11984467/7b4c6862-a4c7-4ea3-9b9e-2664ba378ace)
This does not seem right or we need to use bal-stack? There is no need for right arrow?
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nobilo** [comment]
@lazaki  also has more info about this :)

**Comment by hirsch88** [comment]
done with #885 and #887 
will be released soon
