### ISSUE TITLE
Input field: 

### ISSUE THREAD

**Issue by StefaanSaeys** [baloise/design-system#898]
### Current Behavior

Input field: when I search for eg street name , I can choose options from a dropdown list. 

When I manually type the whole street name inclusive capital / lower letters in the input field ; the right option appears, but I can't select it.

### Expected Behavior

When I type the full name of my search, the right option appears in the dropdown menu and I can select this.

### Steps to Reproduce

https://contact.baloise.be/autoverzekering/start-1

### Version

13

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Device

Mobile, Tablet, Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Will be done in #723
