### ISSUE TITLE
🐛 fix(bal-carousel-item): altTag missing

### ISSUE THREAD

**Issue by janineKleessen** [baloise/design-system#924]
### Current Behavior

It is not possible to set a alt attribute to the images of the carouselietems

### Expected Behavior

bal-carousel-item needs the alt-tag

### Steps to Reproduce

regular usage

### Version

13.2.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
will be done with #926
