### ISSUE TITLE
:bug: fix(datepicker): select days from previous month no longer possible (worked before)

### ISSUE THREAD

**Issue by jochenpilger** [baloise/design-system#930]
### Current Behavior

after upgrading to newest DS version, the business misses the former possibility to select a one of the last days from the previous month in the current month view.

if in this case a mandate of 29.5./30.5. or 31.5. (grayed out) has validity we can no longer click on this but must first change the month above. Previously this always worked. (it's not a big deal but since it worked before, I'm reporting it anyway).
see screenshot

![datepicker](https://github.com/baloise/design-system/assets/39954544/60516789-0693-413e-a0a0-c9be0f709339)
### Expected Behavior

possible to select e.g. 31.05. n the view of June

### Steps to Reproduce

1. open calender
2. try to select the last the of the previous month
3. datepicker should take that date

### Version

13.0.0

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
will be done in #695
