### ISSUE TITLE
🐛 fix(bal-number-input): Validation broken

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#934]
### Current Behavior

The pattern passed to the input contains undefined values and min and max don't seem to have any influence

### Expected Behavior

pattern should be correct format and min and max should restrict possible values

### Steps to Reproduce

regular usage

### Version

13.2.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mladenplaninicic** [comment]
Hi @GinaBiondo-aperto, we don't validate numbers, min and max values are only passed to the native input element.

**Comment by GinaBiondo** [comment]
Hey @mladenplaninicic, thanks for your reply :) So min and max are not supposed to actually do anything? And the pattern? It contains "undefined"

**Comment by hirsch88** [comment]
Hi @GinaBiondo-aperto 

Found issue. PR is open will be released in the next release

**Comment by GinaBiondo** [comment]
There is still an error concerning the input pattern: 

<img width="393" alt="Bildschirmfoto 2023-07-05 um 16 31 25" src="https://github.com/baloise/design-system/assets/72393447/404ee968-4872-4e4e-9a09-b2a29b9890c5">
