### ISSUE TITLE
:speech_balloon: question(button): icon color

### ISSUE THREAD

**Issue by fynnhaeny** [baloise/design-system#937]
### Question

Is it possible to change the color of an icon? Which is in a button.

Example:
![image](https://github.com/baloise/design-system/assets/107040498/8f0f0b05-36a4-43a4-8f85-68e53f912312)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @fynnhaeny 

why do you want to change only the color of the icon?
icon should always have the same color as the text.

**Comment by fynnhaeny** [comment]
hi @hirsch88 

thank you for your answer

as you can see, the icon is still blue and this isnt that beautiful
![image](https://github.com/baloise/design-system/assets/107040498/7380dd2a-381e-4e6b-b4e5-aa628890c96a)
but I want the icon to turn red, is this possible?

**Comment by hirsch88** [comment]
hi @fynnhaeny,

this is not possible since it is not supported by the design.

however you could customise that with our CSS variables.

[Docs how to do that](https://design.baloise.dev/?path=/docs/development-theming--page)

[Icon variables](https://design.baloise.dev/?path=/docs/components-icon--basic#theming)


```
  --bal-icon-color-grey: var(--bal-color-grey-5)
  --bal-icon-color-grey-light: var(--bal-color-border-grey-dark)
  --bal-icon-color-success: var(--bal-color-success)
  --bal-icon-color-warning: var(--bal-color-warning)
  --bal-icon-color-danger: var(--bal-color-danger)
  --bal-icon-color-danger-dark: var(--bal-color-danger-5)
  --bal-icon-color-danger-darker: var(--bal-color-danger-6)
  --bal-icon-color-primary: var(--bal-color-primary)
  --bal-icon-color-primary-dark: var(--bal-color-primary-6)
  --bal-icon-color-blue: var(--bal-color-primary)
  --bal-icon-color-light-blue: var(--bal-color-light-blue-5)
  --bal-icon-color-primary-light: var(--bal-color-primary-3)
  --bal-icon-color-white: var(--bal-color-white)
```
