### ISSUE TITLE
a11y: fix(bal-navigation): invalid aria-attribute

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#948]
### Current Behavior

Currently the attribute aria-label-main is used. This is not a valid aria attribute

### Expected Behavior

Only use valid aria attributes

### Steps to Reproduce

regular usage

### Version

13.4.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
will be done with #911
