### ISSUE TITLE
feat(bal-popup | Navigation): Focus on first Element / Input in popup

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#950]
### Summary

When opening the popup the first element (ideally an input) should be in focus to give a better user experience. This behavior should be optional.

### Use Case

This should be used in the navigation search popup to set the focus on the search input after clicking the opening button.

### Preferred Solution

An optional attribute to be set on the popup component to control this behavior would be nice.

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
will be done in #911
