### ISSUE TITLE
:bug: fix(bal-select): Using remote values label not shown when values are fetched from backend

### ISSUE THREAD

**Issue by whvneo** [baloise/design-system#956]
### Current Behavior

Currently the bal-select shows only the id when "selectionOptional" is set to true

### Expected Behavior

It should show the label from the list provided via an API call. The "select" method is not available on BalSelect in 

### Steps to Reproduce

Have a look at the Stackblitz: [https://stackblitz.com/edit/stackblitz-starters-g4xt53?file=src%2Fmain.html](https://stackblitz.com/edit/stackblitz-starters-g4xt53?file=src%2Fmain.html)

### Version

13.4.4

### Browsers

Chrome

### Device

Desktop

### Code Reproduction URL

https://stackblitz.com/edit/stackblitz-starters-g4xt53?file=src%2Fmain.ts

### Additional Information

When the list for "bal-select-option" is fetched from the api, the bal-select should redraw and show the correct label for the given id. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @whvneo 

Your example was not correct. Please check out our documentation below to the methods of components:
https://design.baloise.dev/?path=/docs/development-components--page#methods

Here is your example updated according do the above documentation.
https://stackblitz.com/edit/stackblitz-starters-7c5aic?file=src%2Fmain.ts

**Comment by whvneo** [comment]
Oups, thanks for that quick answer..... I didn't read that part of the documentation.... Shame on me :-)
