### ISSUE TITLE
:bug: fix(bal-select): control value accessor of bal-select broken in case of turned on typeahead

### ISSUE THREAD

**Issue by Zankel-Engineering** [baloise/design-system#961]
### Current Behavior

Hello folks,

we use your design system in a product :-). In the application we rely heavily on reactive forms. Means we use the reactive form to model the data and implement our own control value accessor components. In one of the components we have the bal-select, which we use with a fuzzy search to choose a profession, since the list of possible professions is to long and will lead to problems with too many DOM-nodes without the prefiltering. It is possible to save and restore the model. In case of a restore I can see, that the value is correctly set on the parent formgroup, the bal-select also is filtered down to just this one value, but the view is not correct, since the typeadhead is still empty.

Please see attached screenshot:
<img width="835" alt="bal-select" src="https://github.com/baloise/design-system/assets/43412711/45db64cf-07e8-46ba-8dc7-c99ea061f34b">

### Expected Behavior

The value is correctly set.

### Steps to Reproduce

1. Build a parent-component with a form-group
2. Build child-component as control-value-accessor with a childform
3. Add the bal-select with typeahead to the child-component
4. Set a value on the parent-form-group that matches the options

### Version

13.0.0

### Browsers

Chrome, Microsoft Edge

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zankel-Engineering** [comment]
Hi guys, I guess this issue is not on the base application side. But you are never sure. I closed the other one, their I offered that we could try to get the design system running on the VDI, so that I can take some burden from your shoulders at least for the bugs that occur in the base application and if not wished I could make better bug reports if I would be able to debug the design system on the VDI. Let me know what you are thinking?

**Comment by Zankel-Engineering** [comment]
Hi guys, while further exploring the issue I recognized that for example when I have the control value accessor around the bal-select in a modal window it only occurs every second time. I am not sure if that helps. I also tried to reset the issue the value after a delay, but this didn't fix the problem.

**Comment by hirsch88** [comment]
deprecated component
