### ISSUE TITLE
:bug: fix(bal-select): event-emitters seem to have problem in the Angular proxy

### ISSUE THREAD

**Issue by Zankel-Engineering** [baloise/design-system#964]
### Current Behavior

Hello folks,

we develop an application with your design system. While developing our application we recognized that there seem to be problems with the event-emitters in the Angular proxy around the web components. Let me explain with pictures:

<img width="1270" alt="event-emitter" src="https://github.com/baloise/design-system/assets/43412711/2d625bea-58e0-4c32-b0be-50c1859d6ad1">

As you can see the method is defined in javaScript, but when I type something the event-emitter doesn't fire an event on the oberservable, which is kinda crazy, cause event-emitters are nothing else then subjects.

Working with a stream here has certain advantages, since we could operate on the stream and prevent unnecesary code execution and change detection.

### Expected Behavior

The event-emitter fires events on the observable.

### Steps to Reproduce

1. Add a balselect to a component.
2. Get a reference to it with the viewChild-Dectorator
3. Operate on a stream from an event-emitter of the component with the asObservable conversion method

### Version

13.0.0

### Browsers

Chrome, Microsoft Edge

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
This can not be done with RX.js, due to the fact that it can not handle the events correctly. it somehow duplicates each component event, wich can cause side effect in an application
