### ISSUE TITLE
🐛 fix(bal-input-slider): Track Position not correct when min is used

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#967]
### Current Behavior

The slider track position is not calculated correctly, when the min attribute is used.

Using a min greater then 0 will always mess up the position:
<img width="1374" alt="Bildschirmfoto 2023-06-22 um 10 29 11" src="https://github.com/baloise/design-system/assets/72393447/78914b15-c6d6-419e-bac6-05f7ecebc3e8">

### Expected Behavior

Track position should match value und thumb position

### Steps to Reproduce

Usage with min attribute greater then 0

### Version

13.4.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
will be done with #724
