### ISSUE TITLE
:sparkles: feat(modal): a reference to the class instance would make things easier in Angular

### ISSUE THREAD

**Issue by Zankel-Engineering** [baloise/design-system#974]
### Summary

Currently we only get the class template in component and in componentProps the outputs seems to be missing. I doubt that updating them will have any impact on the class instance in memory.

### Use Case

Expected would be that we have a pointer on the class instance in memory to interact with the component. In Ionic this behaviour is implemented with the modal-component.

### Additional Information

The bug is a little bit urgent, since we have to workarround the situation which may introduce lot of refactoring work later.

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @Zankel-Engineering 

You get the instance back of the web component. Like Ionic is doing it.
https://ionicframework.com/docs/api/modal#controller-modals

You are able to get the data back like that

```typescript
 const { data, role } = await modal.onWillDismiss();
```

We are not able to provide an angular component instance, this would lead to breaking changes.

If you need constant access to the model maybe to not use the modal service and just use the component.
