### ISSUE TITLE
:bug: fix(icon): Some icons not visible

### ISSUE THREAD

**Issue by whvneo** [baloise/design-system#977]
### Current Behavior

Icon not visible

### Expected Behavior

The icon should be visible

### Steps to Reproduce

1. Create new Angular project
2. setup BDS to work
3. show simple icon or button with icon with "+" is working
4. "logout" is not working
5. "search" is not working

### Version

13.5.0

### Browsers

Chrome

### Device

Desktop

### Code Reproduction URL

https://stackblitz.com/edit/bds-issue-977?file=src%2Fmain.html

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mladenplaninicic** [comment]
Hi @whvneo, by default icons are not loaded by Design System. Here is the documentation how to import them https://design.baloise.dev/?path=/docs/foundation-icons-development--page#usage.
