### ISSUE TITLE
:sparkles: feat(icons): Use icons in HTML

### ISSUE THREAD

**Issue by dweber019** [baloise/design-system#978]
### Summary

According to https://design.baloise.dev/?path=/docs/foundation-icons-development--page#import-into-the-component
there isn't a simple way to use the icons in a HTML & JS app.

So we can't do something like
```
import { balIconAccount } from '@baloise/design-system-icons'
```

even the provided `index.js` throws an error.
![image](https://github.com/baloise/design-system/assets/1021324/76e19efd-5b96-4527-9028-d93e8140a23d)
![image](https://github.com/baloise/design-system/assets/1021324/6ebc646e-0a68-4204-ae96-ecb73252a11d)

### Use Case

Using HTML & JS. We don't have any angular capabilities and we just understand JS supported natively by the browser.

### Preferred Solution

Maybe you could provide a loading mechanism that the following list get's extended.
![image](https://github.com/baloise/design-system/assets/1021324/4d30f2ef-2a33-47d2-a19d-d9a762e5eeae)

### Additional Information

Currently my workaround is to copy&past svg code.
![image](https://github.com/baloise/design-system/assets/1021324/ca2d1320-7e7b-4a9e-82a9-26ecc9c1a0e5)

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @dweber019,

Try to use  the ES module file with script type module, then it should work fine.

```html
<script type="module">
      import { balIconAccount } from './dist/index.esm.js'

      console.log('balIconAccount', balIconAccount)
</script>
```

**Comment by dweber019** [comment]
Can't use type module as we have no control how js files are loaded in the header section.
