### ISSUE TITLE
:bug: fix(checkboxGroup): Class-variable is accessed in a loop

### ISSUE THREAD

**Issue by Zankel-Engineering** [baloise/design-system#981]
### Current Behavior

Hi folks,

we are currently building an Angular-application with your design system. While developing it we recognized that we ran into an issue with the checkbox-group. It seems like the issues is coming from accessing a class variable inside a loop, of which the content seems to be changed while the loop is executed. Please see the screenshot. The input values are stable as you can see.

<img width="1280" alt="chekbox" src="https://github.com/baloise/design-system/assets/43412711/abae6bef-600f-4bb5-a761-151c9533c3a0">

### Expected Behavior

No exception is thrown

### Steps to Reproduce

1. Add a checkbox group as form-control
2. Check and uncheck checkboxes in the group

### Version

13.0.0

### Additional Information

ce.ts:99  ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'toString')
TypeError: Cannot read properties of undefined (reading 'toString')
    at isChecked (bal-checkbox_2.entry.js:401:20)
    at bal-checkbox_2.entry.js:408:28
    at Array.forEach (<anonymous>)
    at CheckboxGroup.sync (bal-checkbox_2.entry.js:407:28)
    at CheckboxGroup.<anonymous> (bal-checkbox_2.entry.js:273:12)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1429:21)
    at resolvePromise (zone.js:1211:31)
    at zone.js:1118:17
    at zone.js:1134:33
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1429:21)
    at CheckboxGroup.onOptionChange (asyncToGenerator.js:21:1)
    at CheckboxGroup.valueChanged (bal-checkbox_2.entry.js:319:14)
    at index-e015dbc8.js:1608:29
handleError @ core.mjs:7635

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mladenplaninicic** [comment]
Hi @Zankel-Engineering, can you please create a codesandbox example so we can reproduce the issue? Thank you

**Comment by Zankel-Engineering** [comment]
Hi Mladen sure I could do this, but wouldn't it be better if we could somehow get the sources running on the VDI so that I can get a little burden from your shoulders and open pull requests for you guys that you can review then?

**Comment by Zankel-Engineering** [comment]
I can't reproduce the issue which is kind of obscure, because I didn't update the library as far as I can remember and the code still seems to be the same. I will close the issue and reopen it if it occurs again.
