### ISSUE TITLE
:bug: fix(Validators): BalValidators seem not to follow the Angular standard

### ISSUE THREAD

**Issue by Zankel-Engineering** [baloise/design-system#982]
### Current Behavior

Hi guys,

it seems like the BalValidators don't follow the Angular standard because the return of the ValidatorFunction needs to be {[key: string]: boolean} | null (ValidationErrors | null) and they only return a boolean. I don't know if I don't use them correctly?

### Expected Behavior

Validation needs to work

### Steps to Reproduce

1. Register a form-control in a form with BalValidators attached
2. Set the form control to an invalid state
3. Check the valid property of the containing formGroup

### Version

13.0.0

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Device

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @Zankel-Engineering 

This is not in the Design System. This belongs to the Web Community. 
[web-app-utils](https://github.com/baloise/web-app-utils)

I created there an issue => https://github.com/baloise/web-app-utils/issues/60

Please present that in the Web Community meeting and ask them what to do

Thank you
