### ISSUE TITLE
:speech_balloon: question(stories): properties table block

### ISSUE THREAD

**Issue by remi-martinez** [baloise/design-system#986]
### Question

I was wondering how you did manage to customize and add a "attribute" column _(and remove the "control" column)_ down here, as I can't find it directly in the source code :

![image](https://github.com/baloise/design-system/assets/64494563/ed1f0fcd-719b-42a8-9193-c13648c81147)

Also, can this customization work in Storybook 7 (working on a personal project) ?

### Additional Information

By default, the table look like this (properties and attributes are sorted in collapsable sections) :
![image](https://github.com/baloise/design-system/assets/64494563/ac29d6b4-7742-49ee-95dd-06a8b90b8033)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @remi-martinez 

Our api docs are generated by stencil and not by storybook. I guess that is the difference.

**Comment by remi-martinez** [comment]
Thank you for your response @hirsch88. That makes sense. I guess you did use this kind of solution with Stencil https://stenciljs.com/docs/docs-json

**Comment by hirsch88** [comment]
Yes and also wrote some special doc generator output
