### ISSUE TITLE
:sparkles: feat(bal-icon): add "outline" as a property

### ISSUE THREAD

**Issue by FilipMarkovski** [baloise/design-system#997]
### Summary

There are icons that are just an "outline" version of the existing ones.  While they are represented in the Figma board named "Iconography", they aren't included in the design-system-icons lib

outline version:
![image](https://github.com/baloise/design-system/assets/24799235/e74ee8e8-c3c4-469d-a1f3-c268563be27a)

fill version (this one exists in the lib)
![image](https://github.com/baloise/design-system/assets/24799235/53b57576-ca29-4dab-b066-aad93c4f8870)

### Use Case

We are using that outlined version of the icon in our rebranded version of the app.

The case can also apply for the simple fact that there are icons that are missing, and are just a different version of the already existing icon. "inverted" property doesn't solve the issue, because that just changes the color of the same svg. The svgs differ in svg content.

### Preferred Solution

Write an "outline" (or "outlined") property for the bal-icon component

### Additional Information

Btw, your "Code of Conduct" link isn't working

### Will this feature introduce breaking changes?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FilipMarkovski** [comment]
Btw the outlined version of the icon is displayed in the figma board as "fully implemented", and not the filled version. The filled icon version is not over there at all, but it is in the code lib

**Comment by hirsch88** [comment]
@clastzoo We need to look at that what we do here

**Comment by hirsch88** [comment]
@FilipMarkovski The technical DS has the correct icon Figma will be updated
