### ISSUE TITLE
:wrench: chore(BalAccordion): color support for accordion

### ISSUE THREAD

**Issue by predrag-arsic** [baloise/design-system#998]
### Summary

As a helper component to provide additional info to customer we used **BalAccordion** with grey background to distinguish it from rest of the form. Needless to say, this was not pretty CSS hack, so we would like for the backround color support to be added to BalAccordion component.

![Screenshot 2023-07-11 at 10 30 34](https://github.com/baloise/design-system/assets/19598046/22230d1e-9d50-43ad-a211-262ab8616d84)

This would be the desired look (using _--bal-color-grey-2_) in this example

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @predrag-arsic just set the color with a custom css class like has-background-grey-2
